examples/filter2/main.go
waku/v2/node/wakunode2.go
waku/v2/protocol/filter/waku_filter.go

Add missing code for UnsubscribeFilter

Add UnsubscribeFilter

---

examples/chat2/go.mod
examples/chat2/go.sum
examples/chat2/main.go
waku/v2/node/wakunode2.go
waku/v2/protocol/lightpush/waku_lightpush.go
waku/v2/protocol/store/waku_store.go
waku/v2/protocol/store/waku_store_protocol_test.go

 refactor: add Next() and create Query and Result structs

---

examples/chat2/chat.go
tests/connection_test.go
waku/node.go
waku/v2/broadcast.go
waku/v2/broadcast_test.go
waku/v2/node/wakunode2.go
waku/v2/protocol/lightpush/waku_lightpush_test.go
waku/v2/protocol/relay/subscription.go
waku/v2/protocol/relay/waku_relay.go
waku/v2/protocol/relay/waku_relay_test.go
waku/v2/protocol/store/waku_store.go

```go
node, _ = wakunode.New()
// Relay
node.Relay().Publish(...)
node.Relay().Subscribe(...)
```

refactor: relay

---

waku/v2/node/wakunode2.go

This helps when going to and back from Airplane mode.

Iterate through Peerstore in startKeepAlive()

---

.gitignore
Makefile
ci/Jenkinsfile
examples/basic2/main.go
examples/filter2/main.go
examples/peer_events/main.go

Add command for generating coverage
fixes #115

test: build example in jenkins

---

go.mod
go.sum
waku/node.go
waku/options.go
waku/v2/rpc/codec.go
waku/v2/rpc/debug.go
waku/v2/rpc/waku_rpc.go

feat: Add first endpoint for rpc server

---

README.md
waku/v2/rpc/codec.go
waku/v2/rpc/coded_test.go
waku/v2/rpc/waku_rpc.go

Respect the rfc: get_waku_v2_debug_v1_info and convert to: Debug.GetV1Info
Also add the WIP in the readme

feat: Use correct rpc method name

---

waku/v2/discovery/resolver.go
waku/v2/node/connectedness_test.go
waku/v2/node/waku_payload.go
waku/v2/node/wakunode2.go
waku/v2/node/wakuoptions.go
waku/v2/protocol/envelope.go
waku/v2/protocol/lightpush/waku_lightpush.go
waku/v2/protocol/store/waku_resume_test.go
waku/v2/protocol/store/waku_store.go
waku/v2/protocol/store/waku_store_pagination_test.go
waku/v2/protocol/store/waku_store_persistence_test.go
waku/v2/protocol/store/waku_store_query_test.go
waku/v2/utils/time.go
waku/v2/utils/time_test.go

Also do some linting and add documentation for some functions

refactor: use envelopes in the store

---

waku/v2/protocol/filter/waku_filter.go
waku/v2/protocol/filter/waku_filter_test.go

Adds a missing lock to the subscribers array

test: unsubscribe to filter

---

waku/options.go
waku/v2/node/wakunode2.go
waku/v2/protocol/filter/waku_filter.go
waku/v2/protocol/filter/waku_filter_test.go

Moves the filter logic from wakunode2 to waku_filter

refactor: filter

---

examples/filter2/main.go
waku/node.go
waku/options.go
waku/persistence/store.go
waku/persistence/store_test.go
waku/v2/node/wakunode2.go
waku/v2/node/wakuoptions.go
waku/v2/protocol/filter/waku_filter_test.go
waku/v2/protocol/lightpush/waku_lightpush_test.go
waku/v2/protocol/store/message_queue.go
waku/v2/protocol/store/message_queue_test.go
waku/v2/protocol/store/waku_resume_test.go
waku/v2/protocol/store/waku_store.go
waku/v2/protocol/store/waku_store_persistence_test.go
waku/v2/protocol/store/waku_store_protocol_test.go
waku/v2/protocol/store/waku_store_query_test.go

feat: message retention policy for wakustore

---

waku/v2/protocol/lightpush/waku_lightpush.go
waku/v2/protocol/lightpush/waku_lightpush_option.go

the relay node being present or not

refactor: lightpush options and be more explicit about

---

waku/v2/protocol/relay/waku_relay.go
waku/v2/rpc/relay.go
waku/v2/rpc/waku_rpc.go

Let me know what you think of the unsubscribe and recover part in waku relay

feat: Add relay rpc methods

---

waku/v2/rpc/coded_test.go
waku/v2/rpc/debug_test.go
waku/v2/rpc/relay_test.go
waku/v2/rpc/store.go
waku/v2/rpc/store_test.go
waku/v2/rpc/util_test.go
waku/v2/rpc/waku_rpc.go
waku/v2/rpc/waku_rpc_test.go

feat: Add rpc store

---

README.md
examples/basic2/go.mod
examples/basic2/go.sum
examples/basic2/main.go
examples/chat2/chat.go
examples/chat2/go.mod
examples/chat2/go.sum
examples/chat2/main.go
examples/filter2/go.mod
examples/filter2/go.sum
examples/filter2/main.go
waku/v2/protocol/relay/waku_relay.go
waku/v2/protocol/topic.go
waku/v2/protocol/topic_test.go

This adds some helpers to create ContentTopics and PubsubTopics following the format defined in the spec.
In a separate PR I'll replace relay.Topic by these new structs.

feat: 23/WAKU2-TOPICS

---

waku/v2/rpc/filter.go
waku/v2/rpc/private.go
waku/v2/rpc/private_test.go
waku/v2/rpc/relay.go
waku/v2/rpc/rpc_type.go
waku/v2/rpc/waku_rpc.go

Plus add missing methods in other services as not implemented yet

feat: Add private service

---

examples/basic2/main.go
examples/chat2/chat.go
examples/filter2/main.go
tests/connection_test.go
waku/node.go
waku/v2/node/wakunode2.go
waku/v2/protocol/filter/waku_filter_test.go
waku/v2/protocol/lightpush/waku_lightpush.go
waku/v2/protocol/lightpush/waku_lightpush_test.go
waku/v2/protocol/relay/waku_relay.go
waku/v2/protocol/relay/waku_relay_test.go
waku/v2/rpc/filter_test.go
waku/v2/rpc/relay.go

since go-libp2p uses string for topics

refactor: remove topic type

---

waku/v2/discv5/discover.go
waku/v2/discv5/discover_test.go
waku/v2/node/wakunode2.go
waku/v2/utils/enr.go
waku/v2/utils/enr_test.go
waku/v2/utils/peer.go
waku/v2/utils/peer_test.go

Also, reorganize code in utils package

fix: wakuflag for ListenAddresses ENR

---

waku/node.go
waku/options.go
waku/try/try.go
waku/try/try_test.go
waku/v2/node/wakunode2.go
waku/v2/node/wakuoptions.go
waku/v2/protocol/filter/waku_filter_test.go
waku/v2/protocol/lightpush/waku_lightpush.go
waku/v2/protocol/lightpush/waku_lightpush_test.go
waku/v2/protocol/relay/waku_relay.go
waku/v2/protocol/relay/waku_relay_test.go
waku/v2/rpc/admin_test.go
waku/v2/rpc/filter_test.go
waku/v2/rpc/relay_test.go

Publish a message with retry to lightpush or relay depending on the number of peers

feat: Implement logic for publish from node

---

examples/basic2/go.sum
examples/chat2/go.sum
examples/filter2/go.sum
go.mod
go.sum
waku.go
waku/node.go
waku/options.go

Fixes #80
Note: I had to change github.com/jessevdk/go-flags to github.com/urfave/cli/v2 since the former does not support setting a true/false value to boolean flags

fix: flag naming inconsistency

---

examples/chat2/Makefile
examples/chat2/fleets.json
examples/chat2/main.go

fix: remove references to fleets.status.im

---

waku/v2/discv5/discover.go
waku/v2/node/wakunode2.go

chore: nim-waku interop test

---

waku/v2/protocol/store/message_queue.go

Implements the same functionality from nim-waku#876
> - The message sender timestamp may not be more than 20 seconds into the future (i.e. ahead of the receiver timestamp. This is to prevent messages from "jumping" the store queue by simply setting the timestamp to the future.
> - Once the store queue is at capacity, a message will not be store if its index is older than the oldest index currently in the queue.

feat: store timestamp validity checks

---

examples/swift-waku/swift-waku.xcodeproj/project.pbxproj
examples/swift-waku/swift-waku/Config.swift
examples/swift-waku/swift-waku/ContentView.swift
examples/swift-waku/swift-waku/DecodedPayload.swift
examples/swift-waku/swift-waku/JsonResult.swift
examples/swift-waku/swift-waku/Message.swift
examples/swift-waku/swift-waku/Response.swift
examples/swift-waku/swift-waku/WakuNode.swift
examples/swift-waku/swift-waku/swift_wakuApp.swift

feat: swift example app - pt1

---

examples/basic2/go.mod
examples/basic2/go.sum
examples/chat2/go.mod
examples/chat2/go.sum
examples/filter2/go.mod
examples/filter2/go.sum
go.mod
go.sum
waku.go
waku/node.go
waku/options.go
waku/v2/node/wakuoptions.go
waku/v2/node/wakuoptions_test.go
waku/v2/utils/enr.go

Fixes #204 
Adds a `--dns4-domain-name` option. The node multiaddresses will be built using this domain name instead of an ip address.

feat: domain name config

---

Makefile

To use, just pass set the path to the go bin you want to use in
the GOBIN env variable:
`GOBIN=/my/bin/go make`.

Allow setting custom go binary when building

---

waku/node.go

fix: increase timeout when dialing peers and add extra logging

---

waku/v2/rest/relay.go

fix: null response obtaining messages from relay

---

waku.go
waku/node.go
waku/options.go

feat: support multiple DNS discovery URLs

---

ci/Jenkinsfile.docker

This way teams can track what deployments happen when.

ci: add Discord notification for successful builds

---

ci/Jenkinsfile.docker

ci: add diff link for previously deployed commit

---

waku/persistence/store.go
waku/v2/protocol/store/waku_store.go
waku/v2/protocol/store/waku_store_pagination_test.go

Matches https://github.com/status-im/nwaku/pull/1215

chore: improve pagination logic

---

library/api.go
mobile/api.go

Adds the `logLevel` config option to waku_new

feat: set log level

---

examples/c-bindings/main.c
library/README.md
library/api_discovery.go
mobile/api_discovery.go

Specs PR: https://github.com/vacp2p/rfc/pull/548

feat: expose dns discovery thru c-bindings

---

waku/v2/protocol/store/waku_store.go
waku/v2/protocol/store/waku_store_protocol_test.go

feat: find by criteria

---

go.mod
go.sum
utils/ntp.go
waku/node.go
waku/v2/rest/waku_rest.go

Signed-off-by: Prajjawalk <prajjawalkhandelwal@gmail.com>

Add: NTP utils

---

library/README.md
library/api.go
library/api_discovery.go
mobile/api.go
mobile/api_discovery.go

feat: add discV5 to c-bindings

---

waku/v2/rest/waku_rest.go
waku/v2/rpc/waku_rpc.go

fix: start rpc/rest with no relay

---

waku/node.go
waku/v2/node/connectedness_test.go
waku/v2/node/wakunode2.go
waku/v2/node/wakunode2_test.go
waku/v2/node/wakuoptions.go
waku/v2/node/wakuoptions_test.go
waku/v2/rest/waku_rest_test.go
waku/v2/rpc/store_test.go
waku/v2/rpc/waku_rpc_test.go

fix: enable store only when `WithWakuStore` is used

---

cmd/waku/flags.go
waku/cliutils/multiaddr.go

feat: use env. variables for arguments

---

library/api_discovery.go
mobile/api.go
waku/v2/discv5/discover.go

Removes the start and stop function for discV5 from the c-bindings

fix(c-bindings): simplify discv5 API

---

docs/api/store.md
waku/v2/protocol/store/waku_store_client.go
waku/v2/protocol/store/waku_store_protocol_test.go

refactor: improve store iterator

---

cmd/waku/flags.go
cmd/waku/main.go
cmd/waku/no_rln.go
cmd/waku/rln.go
go.mod
go.sum
waku/cliutils/altsrc.go

Fixes #98 
Use `--config-file` to pass the path to a .toml file containing the config attributes

feat: load config from toml file

---

waku/v2/discv5/discover.go
waku/v2/node/wakunode2.go
waku/v2/protocol/peer_exchange/waku_peer_exchange.go
waku/v2/protocol/peer_exchange/waku_peer_exchange_test.go

Uses exponential backoff for connecting to peers and use pointer to enode to simplify code

feat: use backedoff connector and discovery

---

cmd/waku/flags.go
waku/node.go
waku/options.go
waku/v2/discv5/discover.go
waku/v2/node/localnode.go
waku/v2/node/wakunode2.go
waku/v2/node/wakuoptions.go
waku/v2/node/wakuoptions_test.go

This replaces the flag `--advertise-address` with `--ext-multiaddr`

feat: advertise custom multiaddresses

---

waku/db.go

fix: invalid in-memory db URL

---

waku/v2/protocol/peer_exchange/client.go
waku/v2/protocol/peer_exchange/protocol.go

FYI: @danisharora099, @fryorcraken

refactor(px): use request-response instead of dialing back

---

waku/v2/protocol/noise/qr.go

Relevant RFC PR:
https://github.com/vacp2p/rfc/pull/575

chore: use base64 url safe encoding for noise

---

library/README.md
library/api.go
mobile/api.go
mobile/config.go

feat(c-bindings): seenTTL

---

flake.nix
go.mod
go.sum
waku/v2/protocol/rln/group_manager/dynamic/dynamic.go
waku/v2/protocol/rln/group_manager/dynamic/handler_test.go
waku/v2/protocol/rln/group_manager/dynamic/web3.go
waku/v2/protocol/rln/group_manager/root_tracker.go
waku/v2/protocol/rln/group_manager/static/static.go
waku/v2/protocol/rln/rln_relay_test.go
waku/v2/protocol/rln/waku_rln_relay.go

roughly equivalent to https://github.com/waku-org/nwaku/pull/1623
Thanks to @rymnc for clearing the doubts regarding on how this functionality should work.

feat: handle chain forks

---

waku/v2/discv5/discover.go
waku/v2/protocol/peer_exchange/enr_cache.go
waku/v2/protocol/peer_exchange/protocol.go

Related to https://github.com/waku-org/go-waku/pull/531

refactor(peerExchange): use lru for storing peers

---

waku/v2/node/wakuoptions.go
waku/v2/protocol/enr/enr.go
waku/v2/utils/ip.go

fix: enodeToMultiaddress when using ipv6

---

flake.nix
go.mod
go.sum
mobile/api.go
tests/utils.go
waku/node.go
waku/v2/connection_gater.go
waku/v2/discovery_connector.go
waku/v2/discv5/discover.go
waku/v2/node/service.go
waku/v2/node/wakunode2.go
waku/v2/node/wakuoptions.go
waku/v2/peers/inherited.go
waku/v2/peers/peerstore.go
waku/v2/protocol/peer_exchange/client.go
waku/v2/protocol/peer_exchange/protocol.go
waku/v2/protocol/relay/waku_relay.go
waku/v2/protocol/relay/waku_relay_test.go
waku/v2/rendezvous/rendezvous.go
waku/v2/rendezvous/rendezvous_test.go
waku/v2/rest/store.go
waku/v2/rpc/admin_test.go
waku/v2/rpc/filter_test.go

- Limit inbound connections to 10 per IP
- Expose gossipsub parameters on WakuRelay
- New peerstore

refactor: various

---

cmd/waku/flags.go

update flag from --topics to --topic as per #584

chore: update flag from --topics to --topic as per #584

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/improvement.md
.github/ISSUE_TEMPLATE/milestone-issue-template.md

Added bug, feature, improvement and milestone issues templates.

Created issue templates

---

tests/utils.go
waku/v2/node/wakunode2.go
waku/v2/node/wakuoptions.go
waku/v2/protocol/filter/client.go
waku/v2/protocol/filter/filter_test.go
waku/v2/protocol/filter/server.go

Includes a refactor of filter v2 tests, plus some minor changes taken from js-waku (https://github.com/waku-org/js-waku/blob/master/packages/tests/tests/filter.node.spec.ts)
Many changed files are due to function renamings done for consistency - not sure if this was the right call.

chore(filter2): test updates

---

ci/Jenkinsfile.tests

We are checking if `JOB_NAME` contains a token `race` to set the default value for `RACE` parameter which decides which tests run.

ci: add RACE parameter to fix conditional

---

waku/v2/node/wakunode2_rln.go
waku/v2/protocol/rln/group_manager/dynamic/dynamic.go
waku/v2/protocol/rln/group_manager/dynamic/handler_test.go
waku/v2/protocol/rln/group_manager/dynamic/metrics.go
waku/v2/protocol/rln/group_manager/root_tracker.go
waku/v2/protocol/rln/metrics.go
waku/v2/protocol/rln/onchain_test.go
waku/v2/protocol/rln/rln_relay_test.go
waku/v2/protocol/rln/waku_rln_relay.go

Adds metrics to rln-relay. It uses the same of metrics defined in nwaku rln's impl

feat: rln metrics

---

waku/v2/discv5/discover.go

Fixes https://github.com/status-im/status-mobile/issues/17115 and CI error on https://github.com/status-im/status-go/pull/3928
h/t @cammellos for the code :) 
Part of https://github.com/waku-org/go-waku/issues/634

fix(discv5): threadsafe peerCh

---

waku/v2/node/wakunode2.go

While playing with circuit relay, I noticed that I wasn't getting assigned any circuit relay address. Exploring the source code of go-libp2p, i noticed that Identify is filtering out dns4 addresses. Adding back an address in this case just means adding the address with a `ConnectedAddrTTL` 
See https://github.com/libp2p/go-libp2p/issues/2550 for more details

fix: add back to peerstore dns4 addresses removed by go-libp2p identify

---

examples/basic2/main.go
examples/chat2/flags.go

Fixes compilation issues introduced on the examples. I extracted the code from #696

fix: content topic usage on the examples

---

waku/v2/peermanager/peer_manager.go
waku/v2/peermanager/peer_manager_test.go

Apply complete fix as per comments in #714.
closes #713

fix: changes as per review comments in #714 and fix test

---

waku/v2/protocol/rln/group_manager/dynamic/dynamic.go
waku/v2/protocol/rln/group_manager/dynamic/membership_fetcher.go

Adding some context to eth errors, logs to see sync progress and processing duration

chore(rln-relay): add logs for fetching events

---

waku/v2/peermanager/peer_manager.go
waku/v2/peermanager/peer_manager_test.go
waku/v2/peermanager/service_slot.go

Removing duplicate definition of relay protocol const.

chore:remove duplicate declaration of relay protocol const

---

.github/workflows/auto_assign.yml
.github/workflows/auto_assign_pr.yml

Create workflow for automatic assignment of a PR to its creator.

Create workflow for automatic assignment of a PR to its creator

---

.github/workflows/auto_assign.yml
.github/workflows/auto_assign_pr.yml

Update auto assign pr gh command

chore: Update auto assign pr gh command

---

ci/Jenkinsfile.docker

Also use Git commit by default if no tag is provided, but do not push.

ci: use latest and stable Docker tags based on job name

---

.github/workflows/auto_assign_pr.yml

fixes the err auto-assigning the PR to its author

fix: auto assign PR

---

.github/CODEOWNERS

Auto-assign PR for review of code owners

Auto-assign PR for review of code owners

---

cmd/waku/node.go
cmd/waku/server/rest/admin.go
cmd/waku/server/rest/admin_api.yaml
cmd/waku/server/rest/waku_rest.go
cmd/waku/server/rest/waku_rest_test.go
cmd/waku/server/rpc/admin.go
cmd/waku/server/utils.go

Admin REST API implementation as per #814 
Test all new API's using postman by uploading the yaml file.

Feat: implement admin rest api

---

waku/v2/protocol/lightpush/pb/validation.go
waku/v2/protocol/store/pb/validation.go
waku/v2/protocol/store/pb/validation_test.go
waku/v2/protocol/store/waku_store_client.go
waku/v2/protocol/store/waku_store_common.go
waku/v2/protocol/store/waku_store_protocol.go

Validates the content of the protobuffers used in store protocol

refactor: validate protobuffer for store

---

waku/v2/discv5/discover.go

Prints a warning if the configured bootnodes don't support the shards you are currently subscribed to

feat: add warning about bootnodes not supporting shards

---

waku/v2/protocol/relay/config.go

Matches https://github.com/waku-org/nwaku/pull/2168

chore: lower dhi to limit amplification factor

---

cmd/waku/node.go
cmd/waku/server/rest/relay.go
cmd/waku/server/rest/waku_rest.go
cmd/waku/server/rest/waku_rest_test.go
waku/v2/protocol/relay/config.go
waku/v2/protocol/relay/waku_relay.go

chore: refactor rest 

---

.github/workflows/lint_pr.yml

chore: conventional commits

---

waku/v2/discv5/discover.go
waku/v2/peermanager/peer_connector.go
waku/v2/peermanager/peer_discovery.go
waku/v2/peermanager/peer_manager.go
waku/v2/peermanager/peer_selection.go

While running go-waku node to connect to TWN, realized that debug logs were not present to help debug what was happening e.g with discv5. So, started adding debug logs that would help debug any scenario.

chore: add debug logs

---

waku/v2/protocol/filter/client.go
waku/v2/protocol/filter/options.go
waku/v2/protocol/filter/options_test.go
waku/v2/protocol/lightpush/waku_lightpush.go
waku/v2/protocol/lightpush/waku_lightpush_option.go
waku/v2/protocol/lightpush/waku_lightpush_option_test.go
waku/v2/protocol/peer_exchange/client.go
waku/v2/protocol/peer_exchange/waku_peer_exchange_option.go

feat: add a new option to specify peer addr for light protocols

---

README.md

Fix the instruction to run waku with Docker

docs: fix docker run instruction

---

README.md
examples/c-bindings/main.c
examples/chat2/README.md
examples/filter2/README.md
waku/v2/protocol/relay/options.go

Fix c-bindings examples with new discovery node.

chore: fix c-bindings example

---

waku/v2/protocol/relay/waku_relay.go

Fixes bug #922 and also added some useful logs

fix: relay unsub issue

---

cmd/waku/server/rest/filter.go
cmd/waku/server/rest/filter_test.go

Handles the requestID as if it were a string (according to .yaml file) and also does a small refactor in the definition of routes
closes #928

fix(rest-filter): requestID is a `string` and refactor routes

---

waku/v2/dnsdisc/enr_test.go

Use mock resolver for unit testing.

chore: fix enr flaky test with local dns resolver

---

waku/v2/protocol/filter/client.go
waku/v2/protocol/filter/filter_test.go
waku/v2/protocol/subscription/subscriptions_map.go

Addresses #933 
Also changed a log in the test to debug to avoid massive logs containing messages.

fix: return appropriate errors in filter unsubscribe

---

waku/v2/discv5/discover.go
waku/v2/peermanager/peer_manager.go

fix: remove extremely noisy logs

---

waku/v2/node/connectedness.go
waku/v2/node/metrics.go
waku/v2/protocol/relay/metrics.go
waku/v2/protocol/relay/waku_relay.go

Add new metrics to be shown in dashboard similar to nwaku.

feat: metrics dashboard

---

waku/v2/protocol/filter/client.go
waku/v2/protocol/lightpush/waku_lightpush.go
waku/v2/protocol/pb/utils.go
waku/v2/utils/logger.go

Improves the logging for filter light node and lightpush

chore: improve light client logging

---

waku/v2/dnsdisc/resolver.go

relate status-mobile [issue](https://github.com/status-im/status-mobile/issues/18063).
relate status-go [PR](https://github.com/status-im/status-go/pull/4563).
status: ready.

feat: Enable immediate dial termination by reusing passed context in GetResolver

---

waku/v2/node/wakuoptions_test.go
waku/v2/protocol/rln/onchain_test.go

Description
Batch of tests for Waku RLN v2 to improve coverage for Group Manager and Node  
Changes
Tests available to run:
cd go-waku/waku/v2/protocol/rln
go test

chore: RLN tests coverage improvement for node gm

---

ci/Jenkinsfile.docker

No longer necessary due to fleet decomissioning:
* https://github.com/status-im/infra-go-waku/issues/18

chore(ci): drop build discord noficiation

---

examples/basic-light-client/main.go

Fixed the example as there were minor issues in it.

chore: fix lightclient example

---

README.md
docs/api/dnsdisc.md
docs/api/filter.md
docs/operators/how-to/configure-dns-disc.md
docs/operators/how-to/configure-store.md
docs/operators/how-to/run.md
docs/tutorials/onchain-rln-relay-chat2.md
examples/android-kotlin/app/src/main/java/com/example/waku/MainActivity.kt
examples/c-bindings/main.c
examples/chat2/README.md
examples/chat2/chat.go
examples/noise/main.go
examples/waku-csharp/waku-csharp/Program.cs
library/c/README.md
waku/v2/node/address_test.go
waku/v2/node/wakunode2_test.go
waku/v2/protocol/enr/enr_test.go

See https://github.com/status-im/infra-nim-waku/issues/91 for details
Mostly done automatically. Some parts manually.

chore: switch wakuv2 fleet to waku

---

cmd/waku/server/rest/waku_rest.go

fix: rest api cors proper usage

---

waku/v2/peermanager/peer_connector.go

While attempting to debug the issue #1086 I noticed that the backoff period was being applied both to succesful connections and unsuccesful, hence why the test case described in #1086 failed to connect to the only peer defined, because initially with discv5 there's a connection to the peer, and a immediate disconnection due to peers not being subscribed to any shard, but this connection attempt (which was succesful, even if there was an immediate disconnection afterwards) ended up increasing the backoff period.
closes #1086

fix(peer-manager): use backoff only on connection errors

---

cmd/waku/server/rest/legacy_store.go
cmd/waku/server/rest/legacy_store_api.yaml
cmd/waku/server/rest/legacy_store_test.go
cmd/waku/server/rest/store.go
cmd/waku/server/rest/store_api.yaml
cmd/waku/server/rest/waku_rest.go
waku/v2/protocol/store/client.go
waku/v2/protocol/store/result.go

feat(REST): storev3 client

---

waku/v2/api/filter.go
waku/v2/api/filter_test.go
waku/v2/protocol/filter/client.go
waku/v2/protocol/subscription/subscription_details.go
waku/v2/protocol/subscription/subscriptions_map.go
waku/v2/protocol/subscription/subscriptions_map_test.go

fixes #1119 completely as there was missing piece. 
Also updated filter API to take care of failed subscriptions automatically and also to look at connection state to decide whether to resubscribe or not.

fix: filter sub issues

---

waku/v2/protocol/filter/common.go
waku/v2/protocol/filter/options.go

Aligning the contentTopic count per request with nwaku.

chore: modifying defaults for filter serviceNode

---

examples/basic-light-client/go.mod
examples/basic-light-client/go.sum
examples/basic-relay/go.mod
examples/basic-relay/go.sum
examples/chat2/go.mod
examples/chat2/go.sum
examples/filter2/go.mod
examples/filter2/go.sum
examples/noise/go.mod
examples/noise/go.sum
examples/rln/go.mod
examples/rln/go.sum
flake.nix
go.mod
go.sum
waku/v2/node/localnode.go
waku/v2/protocol/enr/localnode.go

Fixes #1138 
Requires status-im/go-ethereum@v1.10.25-status.15

fix: panic due to enr having more than 300 bytes

---

waku/v2/api/filter.go
waku/v2/api/filter_test.go
waku/v2/protocol/subscription/subscription_details.go
waku/v2/protocol/subscription/subscriptions_map.go

feat: optimize filter subs

---

waku/v2/node/keepalive.go
waku/v2/node/wakunode2.go

While going through the code, had noticed that allPeersPingInterval is not at all used. 
Hence fixing the same.

fix: ping interval

---

waku/v2/node/keepalive.go
waku/v2/node/wakunode2.go

Ping the filter nodes the node is subscribed to

feat: ping lightpush peers

---

library/c/README.md
library/config.go
library/node.go
waku/v2/node/wakuoptions.go

cc @Ivansete-status @NagyZoltanPeter probably something to consider exposing in c-bindings if not done in nwaku as well.

feat: add clusterID and shards config to c-bindings

---

ci/Jenkinsfile.docker
ci/Jenkinsfile.nix-flake

related issue : https://github.com/status-im/infra-ci/issues/202

ci: disable restart from stage in jenkins
