go.mod
go.sum

The sys package used in go-waku is incompatible with our current build system on ios.
This commit downgrades it so that we can build successfully status-go on darwin.

Downgrade sys package

---

Jenkinsfile
Makefile

This adds a simple `Jenkinsfile` that runs `make lint` and `make test`.
Had to also add a `deps` target that runs `lint-install` to install missing `golangci-lint`.
Jobs folder: https://ci.status.im/job/go-waku/
Resolves: https://github.com/status-im/go-waku/issues/11

ci: add Jenkinsfile that runs lint and test targets

---

go.mod
go.sum
waku/node.go
waku/v2/node/wakunode2.go
waku/v2/node/wakuoptions.go

Adds rendezvous capabilities to go-waku:
You can create a rendezvous server with the `--rendezvous-server` flag
```
make
./build/waku --rendezvous-server --nodekey 1122334455667788990011223344556677889900112233445566778899001122
```
Then, any node that wants to connect to this rendezvous node, needs to add it as a static node, use the flag `--rendezvous` and the flag `--rendezvous-nodes` with the peerId of the rendezvous node:
```
./build/waku --port 0 --rendezvous --staticnodes /ip4/127.0.0.1/tcp/9000/p2p/16Uiu2HAmMGhfSTUzKbsjMWxc6T1X4wiTWSF1bEWSLjAukCm7KiHV --rendezvous-nodes 16Uiu2HAmMGhfSTUzKbsjMWxc6T1X4wiTWSF1bEWSLjAukCm7KiHV --dbpath "./somedatabase.db"
```

feat: rendezvous pt1

---

examples/chat2/main.go
waku/v2/node/wakunode2.go
waku/v2/node/wakuoptions.go
waku/v2/protocol/lightpush/waku_lightpush.go
waku/v2/protocol/lightpush/waku_lightpush_test.go
waku/v2/protocol/store/waku_resume_test.go
waku/v2/protocol/store/waku_store.go
waku/v2/protocol/store/waku_store_persistence_test.go
waku/v2/protocol/store/waku_store_protocol_test.go
waku/v2/protocol/store/waku_store_query_test.go

To reduce the size of wakunode2.go and stop it from becoming a god object. The proper way to consume those protocols functionality will be like this:
```go
node, _ = wakunode.New()
// Lightpush
node.LightPush().Publish(...)
// Store
node.Store().Query(...)
node.Store().Resume(...)
```
In a separate PR I'll do similar changes to Relay and Filter protocols

refactor: store and lightpush

---

waku/v2/protocol/store/message_queue.go
waku/v2/protocol/store/message_queue_test.go
waku/v2/protocol/store/waku_store.go

Fixes #133
It also moves the logic for verification of duplicated messages to the message queue

feat: clean up older records in message queue

---

examples/basic2/main.go
examples/chat2/main.go
examples/filter2/main.go
tests/connection_test.go
waku/node.go
waku/options.go
waku/v2/discv5/discover.go
waku/v2/discv5/discover_test.go
waku/v2/node/connectedness_test.go
waku/v2/node/wakunode2.go
waku/v2/node/wakunode2_test.go
waku/v2/node/wakuoptions.go
waku/v2/node/wakuoptions_test.go
waku/v2/rpc/admin.go
waku/v2/rpc/admin_test.go

feat: discoveryV5 - part2

---

waku/v2/node/wakunode2.go
waku/v2/rpc/relay.go
waku/v2/rpc/relay_test.go
waku/v2/rpc/store_test.go
waku/v2/rpc/waku_rpc.go

The rpc service subscribe to the messages as per the specs here:
https://rfc.vac.dev/spec/16/#get_waku_v2_relay_v1_messages
Let me know if you have a better idea/place on how to implement this. I hesitate to make the relay itself message aware but I feel it is out of his responsabilities. WDYT

feat: implement rcp relay get messages

---

waku/v2/node/wakunode2.go
waku/v2/node/wakuoptions.go
waku/v2/node/wakuoptions_test.go
waku/v2/protocol/store/waku_store.go

The current `WakuNode` implementation references the store as a concrete struct type, rather than an interface. This makes it difficult to replace with an alternative store implementation.
Since the store is initialized inside the the `Start()` function of the `WakuNode`, it is even more difficult to replace. While there is a `MessageProvider` interface that can be replaced, this assumes that a store implementation will want to keep a full list of all messages in memory. That drastically limits the capacity of the store.
- Create a `Store` interface type that can be used on the `WakuNode` struct, representing the public methods of the store.
- Introduce the concept of a `storeFactory`, which is a function receiving a `WakuNode` instance and returning a `Store` interface.
- Create a …

Create pluggable store

---

Makefile
README.md
examples/c-bindings/Makefile
examples/c-bindings/main.c
examples/c-bindings/main.h
examples/c-bindings/nxjson.c
examples/c-bindings/nxjson.h
go.mod
library/api.go
library/ios.go
library/response.go
library/signals.c
library/signals.go
library/types.go
waku/v2/node/waku_payload.go
waku/v2/node/wakuoptions.go

Adds two new targets:
```
make static-library
make dynamic-library
```
This can be used to embed go-waku into other projects, and invoke the following functions via FFI:
```c
// Initialize a waku node. Receives a JSON string containing the configuration
// for the node. It can be NULL. Example configuration:
// ```
// {"host": "0.0.0.0", "port": 60000, "advertiseAddr": "1.2.3.4", "nodeKey": "0x123...567", "keepAliveInterval": 20, "relay": true}
// ```
// All keys are optional. If not specified a default value will be set:
// - host: IP address. Default 0.0.0.0
// - port: TCP port to listen. Default 60000. Use 0 for random
// - advertiseAddr: External IP
// - nodeKey: secp256k1 private key. Default random
// - keepAliveInterval: interval in seconds to ping all peers
// - relay: Enable …
```

feat: c-bindings for waku relay

---

go.mod
go.sum
waku/v2/protocol/filter/waku_filter.go

When pushing messages to subscribers, we want to ensure that a single slow/unavailable subscriber cannot block the entire filter listener. This creates one goroutine per subscriber to ensure speedy delivery.
While the existing implementation will eventually remove failing subscribers, even a single subscriber that is timing out or unavailable can  disrupt all further subscriptions as the handler is returned on error.

Push subscriptions in parallel

---

waku.go
waku/node.go
waku/options.go
waku/v2/utils/logger.go

Zap supports "console" and "json" out of the box with the possibility to add other formats via [custom encoders](https://pkg.go.dev/go.uber.org/zap#RegisterEncoder).
Can be useful to address https://github.com/status-im/go-waku/pull/242#issuecomment-1140737182

Add option for setting the encoding/format for logs

---

logging/logging.go

The logging helpers wrongly assumed timestamps to be microsecond unix time instead of nanosecond.
Fixes #251

logging: fix timestamp assumption micro -> nano

---

waku/v2/node/connectedness_test.go

TestConnectionStatusChanges has a race in it because it's adding to a WaitGroup inside the goroutines managed by the WaitGroup (race detector output below). Oddly enough I stumbled upon it trying to debug flakiness of Test5000 that we were seeing in our test runs. I observed that when the test succeeds it runs in less than 5s locally, but often it times out given even a minute to complete. It would be the subscriber goroutines that would timeout consuming some fraction of the 5000 messages. It seemed something is racing somewhere. Surprisingly race detector didn't reveal anything when running just Test5000, but it tripped when running the test suite for the whole package, pointing at TestConnectionStatusChanges. The error there is fairly clear, fixed here. But I'm not quite sure how does …

Fix race in TestConnectionStatusChanges

---

waku/v2/protocol/filter/filter_subscribers.go
waku/v2/protocol/filter/waku_filter.go
waku/v2/protocol/filter/waku_filter_test.go

This is a follow up to #257, which did not fix the flakiness of Test5000 for us. Trying to run the entire test suite under the race detector uncovered some more races in the filter protocol (see below). One race was from unsafe accesses from the test,  another race was in the protocol implementation where the FilterListener was racing with the onRequest handler over a subscriber's content filters.
```
% go test ./waku/v2/protocol/filter --race --count=1
2022-06-09T11:03:01.758-0400    INFO    gowaku  selecting peer  {"error": "no suitable peers found"}
2022-06-09T11:03:01.758-0400    INFO    gowaku  selecting peer  {"error": "no suitable peers found"}
2022-06-09T11:03:01.901-0400    INFO    gowaku.filter   filter protocol started {"fullNode": false}
2022-06-09T11:03:02.144-0400    INFO …
```

Fix races in filter protocol and tests

---

go.mod
waku.go
waku/node.go
waku/options.go
waku/v2/discv5/discover.go
waku/v2/discv5/discover_test.go
waku/v2/node/localnode.go
waku/v2/node/wakunode2.go
waku/v2/protocol/lightpush/waku_lightpush.go
waku/v2/rpc/codec.go
waku/v2/rpc/debug.go
waku/v2/rpc/debug_test.go
waku/v2/rpc/filter.go
waku/v2/rpc/filter_test.go
waku/v2/rpc/private.go
waku/v2/rpc/private_test.go
waku/v2/rpc/relay.go
waku/v2/rpc/relay_test.go
waku/v2/rpc/rpc_type.go
waku/v2/rpc/store.go
waku/v2/rpc/utils.go
waku/v2/rpc/waku_rpc.go
waku/v2/utils/enr.go

Fixes #244 
Fixes #247 
Partially fixes #214

fix: js-waku / nwaku interop

---

waku/v2/metrics/metrics.go

The metric view declares different key than what is being emitted, consequently the metric doesn't have any tag. It seems the intent was to use the ErrorType tag key.

Fix gowaku_lightpush_errors tag

---

waku/v2/protocol/filter/filter_subscribers.go
waku/v2/protocol/filter/waku_filter.go
waku/v2/protocol/filter/waku_filter_test.go

status-im#260 introduced a subtle recursive read lock issue. Even though `SubscriptionHasContentTopic` runs in a different goroutine than the goroutine created bye `Items()`, that's why an RLock was needed there, it creates a deadlock in its interaction with `onRequest` that attempts to acquire a full lock when adding a subscriber. This creates the situation [described in the docs](https://pkg.go.dev/sync#RWMutex):
> If a goroutine holds a RWMutex for reading and another goroutine might call Lock, no goroutine should expect to be able to acquire a read lock until the initial read lock is released. In particular, this prohibits recursive read locking. This is to ensure that the lock eventually becomes available; a blocked Lock call excludes new readers from acquiring the lock.
So Items() …

Fix filter deadlock

---

logging/context.go
logging/context_test.go

The type assertion in `logging.From` blows up if the `Context` does not have a logger. This PR fixes the assertion and returns nil if there's no logger. Added tests to confirm the fix.

Fix logging.From panic

---

waku/v2/metrics/metrics.go

Register view with tag key `ErrorType` instead of `KeyType`, since `ErrorType` is what the metric is [emitted with](https://github.com/status-im/go-waku/blob/master/waku/v2/metrics/metrics.go#L88-L92).

Fix store error metrics tagging

---

waku/v2/node/wakunode2.go

Sometimes during tear down the node will panic with:
```
panic: send on closed channel
goroutine 10178 [running]:
github.com/status-im/go-waku/waku/v2/node.(*WakuNode).checkForAddressChanges(0x14000824a00)
/Users/snormore/go/pkg/mod/github.com/xmtp/go-waku@v0.0.0-20220726180454-7710a1d099a9/waku/v2/node/wakunode2.go:234 +0x470
created by github.com/status-im/go-waku/waku/v2/node.New
/Users/snormore/go/pkg/mod/github.com/xmtp/go-waku@v0.0.0-20220726180454-7710a1d099a9/waku/v2/node/wakunode2.go:187 +0xe34
```
It looks like `addrChan` is being sent to after it's been closed in `Stop`, so this PR updates it to close `addrChan` in the same goroutine as it's being written/sent to, rather than in `Stop`.

Close addrChan in the writer goroutine

---

waku/v2/protocol/filter/filter_subscribers.go
waku/v2/protocol/filter/filter_subscribers_test.go
waku/v2/protocol/filter/waku_filter.go

This PR fixes the `unsubscribe` function to only remove subscriptions for topics that have a matching `requestId`. This resolves an issue where subscribing to the same content topic in two requests (request id 1 & 2) and calling unsubscribe on request id 2 would also unsubscribe request id 1.
Now a client can subscribe to the same content topic in two requests (request id 1 & 2), unsubscribe from one (request id 2) and request id 1 will stay subscribed.

Verify matching `requestId` before removing subscription

---

go.mod
go.sum
waku/v2/node/waku_payload.go
waku/v2/noise/handshake.go
waku/v2/noise/noise_test.go
waku/v2/noise/patterns.go
waku/v2/noise/payload.go

Implementation of [35/WAKU2-NOISE](https://rfc.vac.dev/spec/35/)
- Handshakes patterns: `XX`,`XXpsk0`, `XK1`, `K1K1`
- Protocols:
- `Noise_K1K1_25519_ChaChaPoly_SHA256`
- `Noise_XK1_25519_ChaChaPoly_SHA256`
- `Noise_XX_25519_ChaChaPoly_SHA256`
- `Noise_XXpsk0_25519_ChaChaPoly_SHA256`
- Handshake state machine
- Support for serializing/deserializing `PayloadV2`

feat: noise

---

waku.go
waku/node.go
waku/options.go
waku/v2/node/wakuoptions.go

Fixes #275 
Adds the flag `--websocket-secure-port` and its alias `--wss-port` to allow setting up different ports for websockets and secure websockets.

feat: add flag to set wss port

---

library/response.go

This way supposedly we will have always separated errors and results as [here](https://rfc.vac.dev/spec/36/#jsonresponse-type)

Separate error and success responses as per the specification

---

mobile/response.go

Same issue in the mobile api.
Similar changes as at #323

Separate error and success responses as per the specification (mobile)

---

Dockerfile
go.mod

Otherwise we get build errors like:
```
note: module requires Go 1.18
```
https://ci.infra.status.im/job/go-waku/job/deploy-test/28/

Dockerfile: update to GO 1.18, update Alpine

---

Makefile

> New apps must target Android 12 (API level 31) or higher;
> Starting in November 2022, app updates must target API level 31 or above
See https://developer.android.com/google/play/requirements/target-sdk and https://apilevels.com/ for more details

test: target android 31

---

library/README.md
library/api.go
mobile/api.go
waku/v2/node/wakunode2.go
waku/v2/node/wakuoptions.go

Adds a new config item: `relayTopics`, which can optionally contain an array of strings representing the topics a node will automatically subscribe to.

refactor(c-bindings): do not subscribe automatically to default waku topic

---

waku/v2/node/address_test.go
waku/v2/node/localnode.go
waku/v2/utils/enr.go
waku/v2/utils/enr_test.go

To run new test:
```
go test -timeout 30s -run ^TestMultiaddr$ github.com/waku-org/go-waku/waku/v2/utils -count 1 -v
```
Edit `waku/v2/utils/enr_test.go` on line 100 to 104 to modify which multiaddresses would get stored in the `multiaddrs` key

fix: adding circuit relay information to enr

---

waku/v2/discv5/discover.go

Looks like there's some race condition when starting/stopping the listener
https://github.com/status-im/status-mobile/issues/15023
We check here that the listener is present to prevent crashing

Check listener not nil

---

library/README.md
library/api.go
library/api_store.go
mobile/api.go
mobile/api_store.go
waku/db.go
waku/node.go
waku/v2/protocol/store/waku_store_client.go
waku/v2/protocol/store/waku_store_protocol_test.go

Allows an application using the c-bindings to act as a storenode
Adds the following config items:
```
- `store`: Enable store protocol to persist message history
Default `false`
- `databaseURL`: url connection string. Accepts SQLite and PostgreSQL connection strings
Default: `sqlite3://store.db`
- `storeRetentionMaxMessages`: max number of messages to store in the database.
Default `10000`
- `storeRetentionTimeSeconds`: max number of seconds that a message will be persisted in the database.
Default `2592000` (30d)
```
And a new function to retrieve data from local database:
```c
// Query historic messages stored in the localDB
// queryJSON must contain a valid json string with the following format:
//
//	{
//		"pubsubTopic": "...", // optional string
//	 "startTime": 1234, // optional, …
```

feat(c-bindings): expose store protocol

---

waku/v2/rpc/rpc_type.go
waku/v2/rpc/util_test.go
waku/v2/rpc/utils.go

Uses base64url encoding as described in https://github.com/vacp2p/rfc/pull/574

fix: use base64url encoding

---

library/README.md
library/api_discovery.go
mobile/api.go
mobile/api_discovery.go
mobile/api_filter.go
mobile/api_lightpush.go
mobile/api_relay.go
mobile/api_store.go
waku/v2/discv5/discover.go
waku/v2/dnsdisc/enr.go
waku/v2/protocol/peer_exchange/waku_peer_exchange.go
waku/v2/utils/enr.go
waku/v2/utils/enr_test.go

This is a breaking change that modifies the `waku_dns_discovery` function response. Instead of returning an array of multiaddresses, it returns an array of objects with the following structure:
```js
{"result":[
// Node 1
{
"peerID":"16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ",
"multiaddrs":[
"/ip4/134.209.139.210/tcp/30303/p2p/16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ",
"/dns4/node-01.do-ams3.wakuv2.test.statusim.net/tcp/8000/wss/p2p/16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ"
],
"enr":"enr:-M-4QCtJKX2WDloRYDT4yjeMGKUCRRcMlsNiZP3cnPO0HZn6IdJ035RPCqsQ5NvTyjqHzKnTM6pc2LoKliV4CeV0WrgBgmlkgnY0gmlwhIbRi9KKbXVsdGlhZGRyc7EALzYobm9kZS0wMS5kby1hbXMzLndha3V2Mi50ZXN0LnN0YXR1c2ltLm5ldAYfQN4DiXNlY3AyNTZrMaEDnr03Tuo77930a7sYLikftxnuG3BbC3gCFhA4632ooDaDdGNwgnZfg3VkcIIjK …
```

feat(c-bindings): expose enr via dns-discovery

---

waku/v2/protocol/relay/waku_relay.go
waku/v2/protocol/relay/waku_relay_test.go

cc: @LNSD in case something similar could be happening in nwaku.
While executing pprof, I got the following results, where the msgIdFn accounts for 29.95% of objects in memory due to the way hashers are created when using `sha256.Sum256` function. To avoid this happening, I'm using a pool so i can reuse hashers
```
File: waku
Build ID: 8a9ce1246202e29639f22ec01594a1f8d7eb753e
Type: inuse_objects
Time: Mar 2, 2023 at 12:52pm (UTC)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 811015, 98.84% of 820504 total
Dropped 113 nodes (cum <= 4102)
Showing top 10 nodes out of 43
flat  flat%   sum%        cum   cum%
245767 29.95% 29.95%     245767 29.95%  github.com/waku-org/go-waku/waku/v2/protocol/relay.msgIdFn
196608 23.96% 53.92% …
```

fix: use sync.Pool for msgId hasher

---

.gitignore
README.md
ci/Jenkinsfile.nix-flake
flake.lock
flake.nix

This way we can build stuff locally using:
```sh
nix build
nix build .#node
nix build .#library
```
Or just start a shell with Go `1.19.x` using:
```
nix develop
```
Which simply has the same environment as the build shell for the node.
One known snag is that there is currently no simple way to keep `vendorSha256` updated to match the contents of `go.mod` and `go.sum`. For more details see:
https://discourse.nixos.org/t/how-should-i-build-a-go-package-from-local-source/19490/8
One way around this would be to have our own `vendor` folder, but that's also a pretty ugly solution that requires manual updating.
Resolves:
* https://github.com/waku-org/go-waku/issues/256

nix: add Nix flake to build node and library

---

flake.nix

Otherwise it fails with:
```
> nix run github:status-im/go-waku
error: unable to execute '/nix/store/xsmhw1yqz5w9bdgfsprxmhcycl7011wz-go-waku/bin/go-waku': No such file or directory
> ls -l /nix/store/xsmhw1yqz5w9bdgfsprxmhcycl7011wz-go-waku/bin
total 37914
-r-xr-xr-x 1 root root 38775544 Jan  1  1970 waku
```
The other option is to change the output binary path from `waku` to `go-waku`, but that would have to be done by either renaming `cmd/waku` to `cmd/go-waku` or some awkward patching of `buildGo119Module`.

nix: fix nix run by setting mainProgram to waku

---

cmd/waku/flags.go
cmd/waku/main.go
examples/noise/go.mod
examples/noise/go.sum
waku/node.go
waku/options.go
waku/v2/node/wakunode2.go
waku/v2/node/wakuoptions.go
waku/v2/rendezvous/rendezvous.go
waku/v2/rendezvous/rendezvous_test.go
waku/v2/utils/peer.go

@cammellos  @fryorcraken @iurimatias @jm-clius @siphiuel 
This 'finishes' the main work related to re-adding rendezvous in go-waku (with an improved API compared to what I had before).
To test this:
```
1. Start service node:
./build/waku --nodekey=1122334455667788990011223344556677889900112233445566778899001122 --rendezvous-server
2. Start a node and connect it to service node:
./build/waku --nodekey=1122334455667788990011223344556677889900112233445566778899001133 --port 0 --rendezvous --rendezvous-node=/ip4/192.168.1.19/tcp/60000/p2p/16Uiu2HAmMGhfSTUzKbsjMWxc6T1X4wiTWSF1bEWSLjAukCm7KiHV
3. Start another node, and connect it to service node:
./build/waku --nodekey=1122334455667788990011223344556677889900112233445566778899001144 --port 0 --rendezvous …
```

feat: rendezvous client

---

waku/v2/node/wakunode2.go
waku/v2/node/wakunode2_test.go
waku/v2/protocol/relay/waku_relay.go
waku/v2/protocol/relay/waku_relay_test.go
waku/v2/protocol/rln/waku_rln_relay.go
waku/v2/rest/relay.go

This also stores the waku message in a cache to avoid having to decode it twice.
RLN validator is also modified to store the messages in the cache
Matches https://github.com/waku-org/nwaku/pull/1537

feat: add WakuMessage validation in gossipsub

---

cmd/waku/flags.go
waku/node.go

Since issue https://github.com/urfave/cli/issues/1272 is closed, and go-waku is already using version greater than 2.14.1, extra env logic can be removed.

refactor: setting nodeKey via GOWAKU-NODEKEY env

---

waku/node.go
waku/v2/protocol/rln/rln_relay_builder.go
waku/v2/protocol/rln/web3.go

- WatchMembershipRegistered func either returns nil, err or Subscription, nil. 
So, subs.Subscribe https://github.com/waku-org/go-waku/blob/master/waku/v2/protocol/rln/web3.go#L197 will fail when there is an err. subs will be nil.
- I think the purpose of `errCh` and `done` in watchNewEvents func is to get the first error while creating a subscription (like if the node doesn't support ws notifications). On such err, application should terminate. But  https://github.com/waku-org/go-waku/blob/master/waku/v2/protocol/rln/web3.go#L205 done might be closed before  `Resubscribe` creates the first subscription internally. Hence, the first subscription error might not be captured.

refactor: fetch membership events

---

ci/Jenkinsfile.tests
flake.nix

This way we don't need to depend on `make deps`.

nix: install golangci-lint in devel shell

---

ci/Jenkinsfile.android
ci/Jenkinsfile.ios
ci/Jenkinsfile.linux
ci/Jenkinsfile.tests

Using `$HOME/go` is bad and you should feel bad.
Also, adding `/usr/loca/go/bin` is a terrible idea.
And `GOCACHE` is poisoning stuff for linter.

ci: fix GOPATH, PATH, and GOCACHE

---

ci/Jenkinsfile.docker

Changes:
* Rename `BRANCH` to `GIT_REF` to indicate tags can be used.
* Default to `stable` for `IMAGE_TAG` on release builds.
* Use `GIT_REF` for specific Docker image tag instead of commit.
* Adjust some comments and descriptions.
Resolves: https://github.com/waku-org/go-waku/issues/516

ci: adjust Docker Jenkinsfile for releases

---

flake.lock
flake.nix

Fixes:
- https://github.com/NixOS/nixpkgs/pull/204278
- https://github.com/NixOS/nixpkgs/pull/228696
Other notable upgrades:
- Bash from `5.1` to `5.2`
- Binutils from `2.39` to `2.40`
- GnuAWK from `5.1.1` to `5.2.1`
- GCC  from `11.3.0` to `12.2.0`
- GNU Make from `4.3` to `4.4.1`
- Go from `1.19.6` to `1.19.8`

nix: upgrade nixpkgs to include xcodeWrapper fixes

---

waku/v2/protocol/relay/waku_relay.go

cc: @Daimakaimura 
To see it in action,  use --log-level=DEBUG  (there's no TRACE level in go-waku)
example output:
```
2023-05-03T10:22:01.526-0400    DEBUG   gowaku.node2.relay      relay/waku_relay.go:399 waku.relay received     {"node": "16Uiu2HAmGZU7iExmPSQ6AbCS64WKrwYMNocScNXoJAfFtuYUHXFU", "topic": "/waku/2/default-waku/proto", "hash": "0xbafff0fdf326a587ff91b74695372dd338d3f412e8bb1413a985d3475be1fdce", "receivedTime": 1683123721512878171, "payloadSizeBytes": 540}
```

feat: add message size and received time to debug log

---

ci/Jenkinsfile.tests

We've had too many leftover containers conflicting with new ones.
Also, no idea why we were joining a single element array.

ci: cleanup Ganache container after tests finish

---

waku/v2/discv5/discover.go

Remove mutex in favour of atomic load and atomic.compareAndSwap to get the same functionality and implement lock-free code.
In iterate function:
Either ctx.Err() or ctx.Done is needed.

refactor(discv5): lock-free via atomics

---

waku/v2/node/wakunode2.go
waku/v2/node/wakuoptions.go
waku/v2/node/wakuoptions_test.go

This allows using both flags without one overriding the other

refactor: add `--ext-ip` and `--dns4-domain-name` values to the list of node multiaddressess

---

waku/node.go
waku/v2/node/wakunode2.go
waku/v2/node/wakuoptions.go
waku/v2/rendezvous/rendezvous.go
waku/v2/rendezvous/rendezvous_test.go

This PR changes the usage for Rendezvous so it's up to the application to choose when to register and discover peers.
For `./build/waku` subscribing to a pubsub topic will immediatly register the pubsub topic in a rendezvous node, and will and will periodically ask for peers to rendezvous points, until achieving `D` peers. (this might change in the future depending on how sharding is implemented in service nodes).
In addition to these behavior changes, this PR also adds some useful functions for sharding: `RegisterShard` and `RegisterRelayShards`

refactor: rendezvous

---

flake.nix
mobile/api.go
waku/node.go
waku/v2/discv5/discover.go
waku/v2/node/keepalive.go
waku/v2/node/localnode.go
waku/v2/node/wakunode2.go
waku/v2/node/wakunode2_test.go
waku/v2/node/wakuoptions.go
waku/v2/protocol/enr/localnode.go
waku/v2/protocol/enr/shards.go
waku/v2/protocol/filter/client.go
waku/v2/protocol/relay/waku_relay.go
waku/v2/protocol/shard.go
waku/v2/protocol/topic.go

- Shards in same cluster are advertised on ENR
- Store().Resume() was moved to app layer
- NoDefaultWakuTopic() was removed since it's the app that must determine whether it subscribes to the default waku topic or not
- Removed `Publish` from WakuNode (not really used and easy to implement in app layer if needed)

feat: subscribe to shards with --topic and refactors

---

tests/utils.go
waku/v2/discovery_connector.go
waku/v2/discv5/discover.go
waku/v2/node/service.go
waku/v2/node/wakunode2.go
waku/v2/node/wakunode2_test.go
waku/v2/protocol/peer_exchange/client.go
waku/v2/protocol/peer_exchange/protocol.go
waku/v2/rendezvous/rendezvous.go
waku/v2/rendezvous/rendezvous_test.go

@cammellos this should fix the issue you ran into while executing mobile integration tests
I added this test to ensure a wakunode can be restarted
```
go test -timeout 300s -run ^TestUpAndDown$ github.com/waku-org/go-waku/waku/v2/node -count 1 -v
```

refactor: make peerConnector subscribe to discovery services and allow wakunodes to be restarted without error

---

cmd/waku/node.go
waku/v2/discovery_connector.go
waku/v2/discv5/discover.go
waku/v2/node/wakunode2.go
waku/v2/protocol/enr/enr.go
waku/v2/utils/multiaddr.go

This PR fixes some issues found while doing a comparison between go-waku and nwaku.
1. Adds two artificial delays to discv5 iterators: When `Next()` is called, if it takes less than 50ms, it wait `50ms - elapsed time` before requesting another peer from DiscV5; and adds a 5s delay every 15 peers.
2. Disables concurrent dialing in peer connector. This should be re-enabled once a performance comparison is done again with PR https://github.com/waku-org/go-waku/pull/597
3. Fixes the multiaddresses sent to the discovery connector since they were missing the `p2p` component
PR made in collaboration with @alrevuelta

fix: p2p circuit and discv5 conns

---

cmd/waku/flags.go
cmd/waku/keygen/command.go
cmd/waku/keygen/flags.go
cmd/waku/keygen/options.go
cmd/waku/main.go
cmd/waku/node.go
cmd/waku/node_no_rln.go
cmd/waku/node_rln.go
cmd/waku/options.go

Moves the logic to generate a key file to its own subcommand, instead of using a flag.
To generate a nodekey file, you can execute the following command:
```
./build/waku generate-key --key-password=.....
```

refactor: move --generate-key to a generate-key subcommand

---

cmd/waku/flags.go
cmd/waku/main.go
cmd/waku/node.go
cmd/waku/options.go
cmd/waku/rest/utils_test.go
library/node.go
waku/persistence/postgres/postgres.go
waku/persistence/sqlite/sqlite.go
waku/persistence/utils/db.go
waku/v2/node/connectedness_test.go
waku/v2/node/wakunode2_test.go
waku/v2/protocol/store/utils_test.go
waku/v2/rendezvous/rendezvous_test.go

This adds new flags already available in nwaku to allow users to execute the vacuum procedure on sqlite databases and choose whether they want to execute migrations or not
cc: @apentori

feat: sqlite vacuum and optional migrations

---

cmd/waku/rest/utils_test.go
waku/persistence/postgres/postgres.go
waku/persistence/sqlite/sqlite.go
waku/persistence/store.go
waku/persistence/utils/db.go
waku/v2/node/connectedness_test.go
waku/v2/node/wakunode2_test.go
waku/v2/protocol/store/utils_test.go
waku/v2/rendezvous/rendezvous_test.go

Minor refactor that removes the functions `WithDB` specific to each RDBMS, that are not used at all, and whose behavior can still be achieved by using `persistence.WithDB`; and reduce the number of returned parameters from `NewDB` while also reducing the responsibility of this function, as there is already a `Migrations` function that can be called, in case we want to obtain the migrations for postgresql/sqlite

refactor: remove unused function and simplify code related to creating db and migrations

---

waku/v2/node/keepalive.go
waku/v2/node/keepalive_test.go

@cammellos noticed that sometimes in mobile, go-waku is too eager to disconnect all peers, with this happening even when peers are connected and working fine. This PR changes the behavior to not immediatly disconnect peers when waking up from sleep, but do it only if pinging the peer fails

chore: keepAlive peer disconnecting peers only on ping failure

---

examples/c-bindings/main.c
library/c/README.md
library/c/api.go
library/c/api_encoding.go
library/c/api_lightpush.go
library/c/api_relay.go
library/discovery.go
library/encoding.go
library/lightpush.go
library/mobile/api.go
library/mobile/api_encoding.go
library/mobile/api_lightpush.go
library/mobile/api_relay.go
library/node.go
library/relay.go

Current c-bindings have encoding functions for both lightpush and relay that while at first view they appear to simplify the process of encoding messages using v1 encryption, in practice, they don't introduce benefits that make their existence worthy of the duplication of code and coupling lightpush and relay bindings to encoding functionality.
This PR refactors away this issue by removing the encryption functions for lightpush and relay, and instead create two functions to perform this operation, similar to how decoding is done.

refactor: remove enc_publish functions and create separate encoding functions instead

---

flake.nix
go.mod
go.sum
waku/v2/protocol/rln/group_manager/dynamic/dynamic.go
waku/v2/protocol/rln/group_manager/dynamic/handler_test.go
waku/v2/protocol/rln/group_manager/static/static.go

Replace inserting/removing members individually by using batch operations with zerokit's `atomic_write`

feat(rln-relay): use batch operations API

---

waku/v2/node/wakunode2.go

Ran tests with race detector enabled which reported 2 race conditions (given below).
Fix done for the same by ordering initialization.
Executed all unit tests with and without race condition.
```
==================
WARNING: DATA RACE
Read at 0x00c001db9fb0 by goroutine 2437:
github.com/waku-org/go-waku/waku/v2/peermanager.(*PeerManager).GroupPeersByDirection()
/Users/prem/Code/go-waku/waku/v2/peermanager/peer_manager.go:106 +0x3c
github.com/waku-org/go-waku/waku/v2/peermanager.(*PeerConnectionStrategy).shouldDialPeers()
/Users/prem/Code/go-waku/waku/v2/peermanager/peer_connector.go:188 +0x228
github.com/waku-org/go-waku/waku/v2/peermanager.(*PeerConnectionStrategy).Start.func1()
/Users/prem/Code/go-waku/waku/v2/peermanager/peer_connector.go:141 +0x4c
Previous write at 0x00c001db9fb0 by …
```

fix: race condition in peermgt initialization reported by race detector

---

waku/v2/peermanager/peer_manager.go

fix relay peer calculation by not invoking FilterPeersByProto if inPeers/outPeers count is 0.

fix: relay peer calculation

---

cmd/waku/node.go

Adds back code that I deleted by mistake in https://github.com/waku-org/go-waku/commit/61cba076bb0a585a33b8fc3187c3b780b0e611b1#diff-1365cc75829d0357d9c3adbd9fbc213f47e9ad86aa02e9e24f1513d84e7de037L109
closes #649

fix: log output and encoding

---

waku/v2/node/localnode.go
waku/v2/node/wakunode2.go

Register to listen for local Node reachability status and log when there are changes to it(Similar to https://github.com/waku-org/nwaku/pull/1472. ). Reachability is determined with help of AutoNAT service.
Note that some deviations would be there due to go-libp2p implementation of AutoNAT.

feat: register for local node's reachability change

---

waku/v2/protocol/rln/group_manager/dynamic/dynamic.go

See https://github.com/waku-org/nwaku/issues/1903 for reasoning behind this change
Part of #655

chore(rln-relay): rename keystore application to `waku-rln-relay`

---

waku/v2/protocol/rln/group_manager/dynamic/dynamic.go
waku/v2/protocol/rln/group_manager/dynamic/handler_test.go
waku/v2/protocol/rln/group_manager/dynamic/metadata.go
waku/v2/protocol/rln/group_manager/dynamic/metadata_test.go
waku/v2/protocol/rln/group_manager/dynamic/web3.go

See https://github.com/waku-org/nwaku/issues/1921 for reasoning behind this fix
- Adds chainID and contract address to RLN metadata
- Adds test unit to verify metadata serialization 
- Returns an error during startup if metadata does not match configuration settings
part of #655

fix(rln-relay): RLN DB should be aware of chain and contract address

---

cmd/waku/flags_rln.go
cmd/waku/node_rln.go
cmd/waku/options.go
examples/chat2/chat.go
examples/chat2/exec.go
examples/chat2/flags.go
examples/chat2/options.go
waku/v2/node/wakunode2.go
waku/v2/node/wakunode2_no_rln.go
waku/v2/node/wakunode2_rln.go
waku/v2/node/wakuoptions.go
waku/v2/node/wakuoptions_rln.go
waku/v2/protocol/relay/waku_relay.go
waku/v2/protocol/rln/group_manager/dynamic/web3.go
waku/v2/protocol/rln/onchain_test.go
waku/v2/protocol/rln/rln_relay_test.go
waku/v2/protocol/rln/waku_rln_relay.go

chore(rln): run rln in all relay pubsubtopics + remove cli flags

---

waku/v2/protocol/filter/client.go
waku/v2/protocol/filter/server.go

The requestID was not being populated when unsubscribing from filter.
I also added the request type to the logs since it's useful for debugging

fix(filterV2): requestID and log request type

---

waku/v2/peermanager/peer_manager.go

Change logLevel of log during to 1 second polling. 
Moved info log to relevant location.
@harsh-98 , let's keep in mind number of info logs we generate.

chore: fix frequent logging from poll

---

README.md

Due to some dependencies the required version is 1.19 now

chore: update Readme to reflect required go version

---

waku/v2/protocol/filter/client.go

A bug reported during testing of the latest go waku, probably we should have some more linting/testing in place to catch these issues?

Check nils when deleting subscription

---

waku/v2/protocol/filter/server.go

one suggestion that was made during today's message reliability call was to add this information to help debug cases where a message appears to have been pushed succesfully to all subscribers yet the message appears to not have been delivered.
To see this change in action, it would require the gowaku fleet to be deployed 
Notice that might add some noise on the logs for full filter nodes, due to these messages being INFO level, but it should be an acceptable tradeoff while dogfooding for filter is in progress. We can do a separate PR in the future to change the log level to DEBUG later

chore: log succesful message pushes

---

.codeclimate.yml
cmd/waku/flags_rln.go
cmd/waku/node_rln.go
cmd/waku/options.go
cmd/waku/rlngenerate/command_rln.go
cmd/waku/rlngenerate/flags.go
examples/chat2/chat.go
examples/chat2/exec.go
examples/chat2/flags.go
examples/chat2/options.go
examples/rln/main.go
waku/v2/node/wakunode2.go
waku/v2/node/wakunode2_rln.go
waku/v2/node/wakuoptions.go
waku/v2/node/wakuoptions_rln.go
waku/v2/protocol/rln/group_manager/dynamic/dynamic.go
waku/v2/protocol/rln/group_manager/static/static.go
waku/v2/protocol/rln/keystore/keystore.go
waku/v2/protocol/rln/keystore/types.go
waku/v2/protocol/rln/onchain_test.go
waku/v2/protocol/rln/waku_rln_relay.go

Extracts the rln keystore to be its own data type so the dynamic group manager does not have to worry about the keystore path and its existence. Also, uses the structure proposed in https://github.com/waku-org/nwaku/issues/1922#issuecomment-1692137198 and https://github.com/waku-org/nwaku/issues/1922#issuecomment-1692192077

refactor: keystore as a data type and store credentials into a map

---

.codeclimate.yml

Excluding some examples from code climate.

chore: exclude directories from code climate

---

waku/v2/discv5/discover.go
waku/v2/node/localnode.go
waku/v2/protocol/shard.go

In https://github.com/status-im/status-go/pull/3944 sharding is introduced for communities,  however 1:1 and group chats use the DefaultPubsubTopic for now. In https://github.com/waku-org/go-waku/pull/696#issuecomment-1700823077 @chaitanyaprem noticed that the current logic of go-waku would not set the shards if there's a mix of static and named sharding. This PR 'fixes' this problem, since currently on status-go we do have a mix of named and static shards.
Once status-go uses static sharding only, then we can remove the option to allow both static and named shards at the same time
Part of https://github.com/waku-org/go-waku/issues/634

fix: allow mixing named and static shards

---

waku/v2/protocol/rln/group_manager/dynamic/web3.go
waku/v2/protocol/rln/web3/web3.go

Sync events from the deployment block instead of doing it from block 0
Part of #655

fix(rln-relay): sync from deployed block number

---

waku/v2/protocol/rln/group_manager/dynamic/dynamic.go
waku/v2/protocol/rln/group_manager/dynamic/metadata.go
waku/v2/protocol/rln/group_manager/dynamic/metadata_test.go
waku/v2/protocol/rln/group_manager/dynamic/web3.go
waku/v2/protocol/rln/group_manager/root_tracker.go
waku/v2/protocol/rln/web3/web3.go

When a node is restarted, and has access to a persisted tree, the window of acceptable roots is not
persisted, and may result in an empty deque. To mitigate this bug, we are persisting the window of acceptable roots in
the rln metadata.
Part of #655

feat: store and retrieve valid merkle roots in RLN db

---

.codeclimate.yml
cmd/waku/flags_rln.go
cmd/waku/node_rln.go
cmd/waku/options.go
examples/chat2/exec.go
examples/chat2/flags.go
examples/chat2/options.go
waku/cliutils/cli.go
waku/v2/node/wakunode2_rln.go
waku/v2/node/wakuoptions.go
waku/v2/node/wakuoptions_rln.go
waku/v2/protocol/rln/group_manager/dynamic/dynamic.go
waku/v2/protocol/rln/keystore/keystore.go
waku/v2/protocol/rln/onchain_test.go

See https://github.com/waku-org/nwaku/pull/1984 for reasoning behind this change
Part of #655

chore(rln-relay): use the only key from keystore if only 1 exists

---

waku/v2/node/wakuoptions.go

Since `wss` is deprecated, this PR adds `tls/ws` to the list of multiaddresses returned by the address factory when using dns4+wss. In the future once js-libp2p adds support to `tls/ws`, we can drop support for `wss` entirely

chore: add tls/ws to address factory

---

waku/v2/protocol/enr/localnode.go

Writing multiaddresses on the ENR `multiaddr` key worked only when there was more than one multiaddress field that should be stored on that field. Most of the time that wasn't a problem, specially since desktop does not use websocket addresses and always has at least 2 circuit relay addresses

fix: loop counter for writing multiaddresses in enr

---

waku/v2/protocol/rln/nullifier_log.go
waku/v2/protocol/rln/onchain_test.go
waku/v2/protocol/rln/rln_relay_test.go
waku/v2/protocol/rln/waku_rln_relay.go

Similar to https://github.com/waku-org/nwaku/pull/1994
Part of #655

chore(rln-relay): clean up nullifier table every MaxEpochGap

---

waku/v2/node/localnode.go
waku/v2/node/wakunode2.go

The node's ENR was being displayed logged it had its information setup, rendering it useless. This PR changes that so the enr is shown after setupENR is executed

fix: log enr only after it has been setup

---

examples/chat2/exec.go
waku/v2/node/wakunode2.go
waku/v2/node/wakunode2_rln.go
waku/v2/node/wakuoptions.go
waku/v2/protocol/envelope.go
waku/v2/protocol/relay/validators.go
waku/v2/protocol/relay/validators_test.go
waku/v2/protocol/relay/waku_relay.go
waku/v2/protocol/relay/waku_relay_test.go
waku/v2/protocol/rln/common.go
waku/v2/protocol/rln/waku_rln_relay.go

This PR guarantees that validators are executed in the order they're appended, that RLN validator is executed as the last validator, and that unmarshalling the WakuMessage is only done once
Part of #655

feat(rln-relay): ensure execution order for pubsub validators

---

cmd/waku/flags_rln.go
cmd/waku/rlngenerate/flags.go
waku/v2/node/wakunode2.go
waku/v2/node/wakunode2_rln.go
waku/v2/protocol/rln/group_manager/dynamic/dynamic.go
waku/v2/protocol/rln/keystore/keystore.go

It's not necessary to have credentials to be a relayer. 
Part of #655

feat: allow running rln with no credentials

---

examples/chat2/chat.go
examples/filter2/main.go
flake.nix
library/filter.go
waku/v2/protocol/filter/client.go
waku/v2/protocol/filter/filter_test.go
waku/v2/protocol/filter/subscribers_map.go
waku/v2/protocol/filter/subscribers_map_test.go
waku/v2/protocol/filter/subscriptions_map.go
waku/v2/protocol/filter/subscriptions_map_test.go

Changes included:
- Rename Topic to PubsubTopic to match spec
- Use set for ContentFilter.ContentTopics
- client.Subscribe() will return an already existing subscription if we happen to run into the same [peer,contentFilter] pair

feat: topic refactors for filter client

---

cmd/waku/flags.go
cmd/waku/main.go
cmd/waku/node.go
cmd/waku/options.go
waku/v2/node/wakunode2.go
waku/v2/node/wakuoptions.go
waku/v2/peermanager/peer_manager.go
waku/v2/peerstore/waku_peer_store.go

Adds a hidden `--force-unreachable` flag that will force the node to use circuit relay. After some seconds the node will have negotiated a circuit relay address if a circuit relay node is added as static node:
```
./build/waku --unreachable --staticnode=/dns4/node-01.do-ams3.go-waku.test.statusim.net/tcp/30303/p2p/16Uiu2HAm9vnvCQgCDrynDK1h7GJoEZVGvnuzq84RyDQ3DEdXmcX7 --wss --wss-key=/path/to/key/file --wss-cert=/path/to/cert/file
```
While testing the functionality with @danisharora099 we noticed that when using an nwaku fleet node, and having wss enabled, the node gets dropped as a peer hence for now I recommend using a node from the gowaku fleet, however the gowaku fleet is returning IP addresses in the list of multiaddresses, so a search/replace must be done to replace the /ip4 address …

feat: force unreachability

---

Makefile
README.md
ci/Jenkinsfile.docker
docs/operators/how-to/run-with-rln.md
docs/operators/quickstart.md
scripts/linux/README.md
scripts/linux/docker-run.sh

We've been using `statusteam` Docker Hub org for a while now which was never intended for public use, and we should be using `wakuorg` instead.
I've also updated references to `statusteam` in documentation and scripts.

ci: use wakuorg Docker Hub organization

---

ci/Jenkinsfile.docker

Nobody is using them and we are just cluttering up the repo.

ci: drop pushing commit tags for Docker

---

waku/v2/peerstore/waku_peer_store.go

Fixes this error:
```
panic: runtime error: slice bounds out of range [2:1]
goroutine 291 [running]:
github.com/waku-org/go-waku/waku/v2/peerstore.(*WakuPeerstoreImpl).RemovePubSubTopic(0xc000018b40, {0xc00088a360, 0x27}, {0x0?, 0x11?})
/home/richard/waku-org/go-waku/waku/v2/peerstore/waku_peer_store.go:169 +0x1dc
github.com/waku-org/go-waku/waku/v2/peermanager.(*PeerManager).peerEventLoop(0xc0003f0c60, {0x26de4d0, 0xc00046e8c0})
/home/richard/waku-org/go-waku/waku/v2/peermanager/peer_manager.go:109 +0x25c
created by github.com/waku-org/go-waku/waku/v2/peermanager.(*PeerManager).Start
```

fix: panic when removing pubsub topic

---

cmd/waku/server/rest/debug_api.yaml
cmd/waku/server/rest/health.go
cmd/waku/server/rest/health_api.yaml
cmd/waku/server/rest/relay_api.yaml
cmd/waku/server/rest/store_api.yaml

Noticed following panic when triggering health API without rln initialization. 
```
2023/09/21 16:34:48 "GET http://127.0.0.1:8645/health HTTP/1.1" from 127.0.0.1:61835 - 000 0B in 56.458µs
2023/09/21 16:34:48 http: panic serving 127.0.0.1:61835: runtime error: invalid memory address or nil pointer dereference
goroutine 761 [running]:
net/http.(*conn).serve.func1()
/usr/local/go/src/net/http/server.go:1854 +0xb0
panic({0x106fe0a60, 0x107c8cf30})
/usr/local/go/src/runtime/panic.go:890 +0x258
github.com/waku-org/go-waku/cmd/waku/server/rest.(*HealthService).getHealth(0x14001289890?, {0x1300b05e0, 0x14001114cc0}, 0x7?)
/Users/prem/Code/go-waku/cmd/waku/server/rest/health.go:33 +0x50
net/http.HandlerFunc.ServeHTTP(0x106fd1700?, {0x1300b05e0?, 0x14001114cc0?}, 0x1400165d33c?) …
```

Fix /health REST API panic

---

waku/v2/peerstore/waku_peer_store.go

Fix panic during RemovePubSubTopics in specific case where there are only 2 elements in slice and last one is being removed.

fix: panic during removePubSubTopic

---

waku/v2/peerstore/waku_peer_store.go

Fix issue introduced in https://github.com/waku-org/go-waku/pull/759
Context: https://github.com/waku-org/go-waku/pull/762#issuecomment-1731212779
**EDIT**: i see that it was independently fixed in https://github.com/waku-org/go-waku/pull/765
@chaitanyaprem can you please review this and decide if the uniqueness check is still worth it?

Fix deleting pubsub topics; only allow adding unique topics

---

library/filter.go
waku/v2/protocol/filter/client.go
waku/v2/protocol/filter/filter_test.go
waku/v2/protocol/filter/options.go
waku/v2/protocol/filter/options_test.go
waku/v2/protocol/filter/subscriptions_map.go

Following changes are included:
- allow creating a new Subscription for same (peer, contentFilter) pairs (this was mistakenly assumed to be wrong and thus removed in https://github.com/waku-org/go-waku/pull/750)
- modify UnsubscribeWithSubscription so that it may close a single subscription only, and not all with a given contentFilter
- merge FilterSubscribe and FilterUnsubscribe options/params, there was some overlap there
- resource cleanup: close subscription channels when unsubscribing
- minor refactors
- test updates

Allow multiple subs for same (peer, contentFilter) pairs

---

waku/v2/protocol/filter/client.go
waku/v2/utils/peer.go

Fixes this errors that appears on the fleet while doing a ping:
```
"(kind: MissingRequiredField, field: "request_id")"
Failed to decode filter subscribe request
```

fix(filter2): add requestID to pings and remove unneeded log

---

cmd/waku/flags.go
cmd/waku/main.go
cmd/waku/node.go
cmd/waku/options.go
waku/v2/node/wakunode2.go
waku/v2/node/wakuoptions.go
waku/v2/peermanager/peer_manager.go
waku/v2/peermanager/peer_manager_test.go

go-libp2p doesn't provide an option to limit peer-store capacity which may cause it to grow unbounded.
This PR includes a config flag which is already there in nwaku to set peerStore capacity. If not set, set it to 5*maxConnections flag.
Ref https://github.com/waku-org/nwaku/pull/1525 
Ran all unit tests.
Ran service-node with and without setting peer-store-capacity flag to confirm values are set appropriately.
Did not add any new unit tests as changes seem trivial.

chore: add config to limit peerstore capacity

---

README.md
docs/api/dnsdisc.md
docs/operators/how-to/configure-dns-disc.md
docs/operators/how-to/run.md
examples/c-bindings/main.c
examples/chat2/chat.go
examples/noise/main.go
waku/v2/dnsdisc/enr_test.go
waku/v2/node/wakunode2_test.go

Enrtrees were regenerated. Need to update the old one.
DNS discoverty should continue to work.

update wakuv2 fleet DNS discovery enrtree

---

cmd/waku/flags.go
cmd/waku/main.go
cmd/waku/node.go
cmd/waku/options.go

Replaces the `--unreachable` flag by `--reachability` which accepts the values `public` or `private` to force circuit relay to work locally.
i.e.:
node1 (circuit relay server)
```
./build/waku --reachability=public --circuit-relay --p=55344 --nodekey=1122334455667788990011223344556677889900112233445566778899001122
```
node2 (unreachable node)
```
./build/waku --reachability=private --staticnode=/ip4/192.168.0.1/tcp/55344/p2p/16Uiu2HAmMGhfSTUzKbsjMWxc6T1X4wiTWSF1bEWSLjAukCm7KiHV -p=0
```
After a while, node2 should receive a circuit relay addr from node1

feat: force reachability

---

Makefile
waku/v2/node/keepalive_test.go
waku/v2/node/wakunode2_test.go

By using -coverpkg flag, coverage is reported from tests that are run outside a package.
In most cases since tests run on waku/v2/node cover many areas under protocol etc, coverage percentage is not updated.
Similarly if tests are in a separate folder, then coverage is not updated for tests run.
Also added few additional tests to improve coverage in recently added code.

Chore: test cov improvement

---

waku/v2/node/wakunode2.go
waku/v2/peermanager/peer_manager.go
waku/v2/peermanager/peer_manager_test.go
waku/v2/peermanager/topic_event_handler.go
waku/v2/peerstore/waku_peer_store.go
waku/v2/protocol/filter/options.go
waku/v2/protocol/lightpush/waku_lightpush_option.go
waku/v2/protocol/peer_exchange/waku_peer_exchange_option.go
waku/v2/protocol/store/waku_store_client.go

Current selectPeer functionality works without taking sharding into consideration. #680  
This enhances to take pubSubTopic or contentTopic into consideration during peer selection.
Ran all existing unit tests.
Added few new ones to validate functionality.

Feat: filter select peer for sharding

---

examples/chat2/chat.go
examples/filter2/main.go
library/c/README.md
library/c/api_lightpush.go
library/filter.go
library/lightpush.go
waku/v2/node/wakunode2.go
waku/v2/peermanager/peer_manager.go
waku/v2/peermanager/peer_manager_test.go
waku/v2/peerstore/waku_peer_store.go
waku/v2/protocol/content_filter.go
waku/v2/protocol/filter/client.go
waku/v2/protocol/filter/filter_test.go
waku/v2/protocol/filter/options.go
waku/v2/protocol/filter/subscribers_map.go
waku/v2/protocol/lightpush/waku_lightpush.go
waku/v2/protocol/lightpush/waku_lightpush_option.go
waku/v2/protocol/lightpush/waku_lightpush_test.go
waku/v2/protocol/peer_exchange/waku_peer_exchange_option.go
waku/v2/protocol/shard.go
waku/v2/protocol/store/waku_store_client.go
waku/v2/protocol/subscription/subscriptions_map.go
waku/v2/protocol/subscription/subscriptions_map_test.go

Update lightPush API to take pubSub topic optionally and derive from contentTopic using autosharding logic.
Ran all unit tests

feat: update lightpush API for autosharding

---

waku/v2/protocol/filter/client.go
waku/v2/protocol/filter/options.go
waku/v2/protocol/filter/options_test.go

Make the options for filter subscription return an err

fix: return errors in FilterSubscribeOption

---

library/mobile/signals.go
library/signals.go

During the library refactor, the mobile package ended up missing the `SignalHandler`. This PR adds it back to the correct folder
closes #790

fix: SignalHandler not exported in mobile package

---

waku/persistence/db_key.go
waku/persistence/store.go
waku/persistence/store_test.go
waku/v2/protocol/store/waku_store_common.go

Fixes an issue reported by @fbarbu15 where a store was not including a message whose timestamp matched the starttime of the query, and also sets the max page size to 20 to match nwaku

fix(store): query time comparison and max rows per page

---

waku/v2/node/address_test.go
waku/v2/node/localnode.go
waku/v2/protocol/peer_exchange/enr_cache.go

Adds ws addresses to the ENR instead of only wss

fix: add ws to enr

---

waku/v2/node/localnode.go

While testing `shards.test` fleet, i noticed that when discv5 endpoint predictor fails, the node's IP address reported in the ENR was 127.0.0.1 regardless of the value being set. With this change, the reported libp2p address will be set as fallback address to be used in case endpoint predictor fails to obtain the IP address

fix: setFallbackIP with reported libp2p addr

---

waku/v2/protocol/filter/client.go

fix: handle empty content topics in filter subcribe and unsubscribe

---

cmd/waku/main.go
cmd/waku/node.go
cmd/waku/node_no_rln.go
cmd/waku/node_rln.go

For errors that require someone to look at what's going on, an exit code `166` is returned. Other errors will return a `1`
closes #797

chore: return custom exit code for non recoverable errors

---

waku/v2/protocol/envelope.go

Previously the digest was missing the pubsub topic and meta. With this PR we just use the message hash as digest so it contains these attributes

fix: msg digest matches msg hash

---

waku/v2/node/wakunode2_test.go
waku/v2/protocol/legacy_filter/filter_map.go
waku/v2/protocol/lightpush/metrics.go
waku/v2/protocol/lightpush/pb/validation.go
waku/v2/protocol/lightpush/pb/validation_test.go
waku/v2/protocol/lightpush/waku_lightpush.go
waku/v2/protocol/pb/validation.go
waku/v2/protocol/relay/validators.go
waku/v2/protocol/relay/waku_relay.go

Validates the content of the protobuffers for both lightpush and relay. In the case of relay, if there's an error while validating the protobuffer, the error string will be returned as a response.
In next PRs I'll add similar validations to the other protocols, assuming this PR is approved!

refactor: validate protobuffers for lightpush and relay

---

waku/v2/protocol/metadata/waku_metadata_test.go

`TestWakuMetadataRequest` is a test intended to check the request/responses for metadata protocol are correct. As such, since we're interested in having deterministic responses, and not disconnect the peers automatically, in this PR I remove the notification process specifically for this test. Other metadata tests are not affected and will still use the notifier mechanism to disconnect peers

fix: do not disconnect peers in `TestWakuMetadataRequest`

---

waku/v2/protocol/relay/broadcast.go
waku/v2/protocol/relay/waku_relay.go

Relay subscription option was not propagated to broadcaster causing subscriber too slow issue when running service node.

fix: propagate relay subscribe opt properly

---

waku/v2/node/wakunode2_test.go
waku/v2/protocol/filter/client.go
waku/v2/protocol/filter/server.go
waku/v2/protocol/legacy_filter/filter_map.go
waku/v2/protocol/legacy_filter/waku_filter.go
waku/v2/protocol/lightpush/metrics.go
waku/v2/protocol/lightpush/pb/validation.go
waku/v2/protocol/lightpush/pb/validation_test.go
waku/v2/protocol/lightpush/waku_lightpush.go
waku/v2/protocol/pb/validation.go
waku/v2/protocol/peer_exchange/client.go
waku/v2/protocol/peer_exchange/protocol.go
waku/v2/protocol/relay/validators.go
waku/v2/protocol/relay/waku_relay.go
waku/v2/protocol/store/waku_store_client.go
waku/v2/protocol/store/waku_store_protocol.go

Renames the `s` variable to `stream`, and uses `stream.Close()` for the success path, and `stream.Reset()` for paths with errors

fix: stream close/reset

---

waku/v2/protocol/store/waku_store_query_test.go

Issue due to macOS/darwin time precision. 
macOS/darwin time is maintained/returned only at microsecond granularity and not at nanosecond granularity. This was the reason for failure of the test. As the test is not meant to depend on timestamps, it has been modified to address the issue.
https://groups.google.com/g/golang-dev/c/DboHw1eCiSc?pli=1

fix: modify store test to not depend on order of msgs

---

waku/v2/protocol/filter/client.go
waku/v2/protocol/filter/pb/validation.go
waku/v2/protocol/filter/pb/validation_test.go
waku/v2/protocol/filter/server.go

Adds validation over filter protocol protobuffers

refactor: validate protobuffer for filter

---

waku/v2/peermanager/peer_connector.go
waku/v2/peermanager/peer_manager.go

Fixes the error seen on this build: 
https://ci.status.im/blue/organizations/jenkins/go-waku%2Fprs%2Frace/detail/PR-828/4/pipeline/

fix: deadlock in peer connector / manager interaction

---

examples/c-bindings/main.c
examples/c-bindings/main.h
library/c/README.md
library/c/api.go
library/c/api_discovery.go
library/c/api_encoding.go
library/c/api_filter.go
library/c/api_legacy_filter.go
library/c/api_lightpush.go
library/c/api_relay.go
library/c/api_store.go
library/c/cgo_utils.c
library/c/cgo_utils.go
library/c/cgo_utils.h
library/encoding.go
library/filter.go
library/lightpush.go
library/node.go
library/relay.go
library/signals.c
library/signals.go
library/store.go
waku/v2/protocol/content_filter.go
waku/v2/protocol/subscription/subscriptions_map.go

Adds an `void* user_data` parameter to all c-bindings API functions so it's possible to use them without having to use global variables
```c
// Initialize a waku node. Receives a JSON string containing the configuration
// for the node. It can be NULL. Example configuration:
// ```
// {"host": "0.0.0.0", "port": 60000, "advertiseAddr": "1.2.3.4", "nodeKey": "0x123...567", "keepAliveInterval": 20, "relay": true}
// ```
// All keys are optional. If not specified a default value will be set:
// - host: IP address. Default 0.0.0.0
// - port: TCP port to listen. Default 60000. Use 0 for random
// - advertiseAddr: External IP
// - nodeKey: secp256k1 private key. Default random
// - keepAliveInterval: interval in seconds to ping all peers
// - relay: Enable WakuRelay. Default `true`
// - …
```

refactor(c-bindings): userdata

---

waku/persistence/postgres/postgres.go
waku/persistence/sqlite/sqlite.go

This will print every 2 minutes the following log line 
```
2023-10-25T21:00:22.973-0400    INFO    gowaku.db-setup sqlite/sqlite.go:63     still vacuuming...      {"node": "16Uiu2HAmJikHbVZJhVtbCvXGwCb6sekZKkZcyP9uU7BcaaAeUWoN"}
```
It's dumb, but it's good UX to indicate that something is happening :)

chore: print a message periodically indicating that VACUUM is still being executed

---

Makefile
cmd/waku/server/rest/relay.go
cmd/waku/server/rpc/filter_test.go
cmd/waku/server/rpc/relay.go
docs/api/lightpush.md
docs/api/relay.md
examples/basic2/main.go
examples/chat2/chat.go
examples/filter2/main.go
examples/noise/main.go
examples/rln/main.go
library/lightpush.go
library/relay.go
tests/connection_test.go
waku/v2/node/wakunode2_test.go
waku/v2/protocol/filter/filter_proto_ident_test.go
waku/v2/protocol/filter/filter_test.go
waku/v2/protocol/legacy_filter/waku_filter_test.go
waku/v2/protocol/lightpush/waku_lightpush.go
waku/v2/protocol/lightpush/waku_lightpush_option.go
waku/v2/protocol/lightpush/waku_lightpush_test.go
waku/v2/protocol/noise/pairing_relay_messenger.go
waku/v2/protocol/relay/options.go
waku/v2/protocol/relay/waku_relay.go
waku/v2/protocol/relay/waku_relay_test.go

I noticed that the API for Lightpush and Relay were somewhat different and would really benefit from having a similar API.
Probably most of this work will go away once named shard support is removed, but whatever :D at least we wont have two separate Publish functions anymore

refactor: publish API for relay and lightpush

---

waku/v2/discv5/discover.go
waku/v2/node/localnode.go
waku/v2/protocol/enr/shards.go
waku/v2/protocol/metadata/waku_metadata.go
waku/v2/protocol/metadata/waku_metadata_test.go
waku/v2/protocol/pubsub_topic.go
waku/v2/protocol/shard.go
waku/v2/rendezvous/rendezvous.go

Use ShardID and ClusterID consistently across project

refactor: fix nomenclature for shards

---

waku/v2/discv5/discover.go

This avoids the problem described in https://github.com/waku-org/nwaku/issues/2162

feat: dont' filter out bootnodes

---

cmd/waku/flags.go
cmd/waku/main.go
cmd/waku/node.go
cmd/waku/options.go
cmd/waku/relay.go
waku/cliutils/bridge.go

On today's message reliability call, creating a bridge between pubsub topics was suggested as a way to solve backward compatibility due to the breaking change introduced in https://github.com/status-im/status-go/pull/4161.
This PR adds a hidden `--bridge-topic=fromTopic:toTopic` flag that can be used to bridge messages from a pubsub topic to another. This is meant to be used with `status.prod` to get messages going from between the default shard and the default pubsub topic (since mixing named and static sharding introduces a lot of problems).
go-waku nodes must be configured with the following flags: 
```
--bridge-topic=/waku/2/default-waku/proto:/waku/2/rs/16/32 --bridge-topic=/waku/2/rs/16/32:/waku/2/default-waku/proto
```
(Maybe we can reuse `gowaku.prod` fleet)

feat: bridge relay topics

---

waku/v2/peermanager/peer_manager.go

@vitvly reported that he sees often in status-go logs the line `"could not retrieve random peer from slot" error="no suitable peers found"`. When reviewing the code, I see that since status-go does not use service slots for retrieving peers supporting filter protocol, but instead depends on the peers that are discovered, this error was generated and logged very frequently.
Since this is not an error per se but a possible outcome of just not having peers registered in the service slots, I did a small refactor to only log errors if different from `ErrNoPeersAvailable`, as well as adding more information to the logs like the protocol and pubsub topic being retrieved.
I also include a minor refactor to not need to use pointers for the peerID

refactor: only log errors different from `ErrNoPeersAvailable` when selecting random peers.

---

cmd/waku/server/rest/filter.go
cmd/waku/server/rest/filter_cache.go
cmd/waku/server/rest/relay.go
cmd/waku/server/rest/utils.go

Topic URL param is not being read properly in relay REST APIs which is causing 500 error. 
```
Hi, I'm trying to use relay via REST API in go-waku (wakuorg/go-waku:latest) as described here https://nagyzoltanpeter.github.io/nwaku-api/index.html#post-/relay/v1/subscriptions but I get errors for relay/v1/messages endpoint
For example trying to publish a message I get a 500
curl -vv -X POST "http://127.0.0.1:63970/relay/v1/messages/%2Fwaku%2F2%2Fdefault-waku%2Fproto" -H "content-type: application/json" -d '{"payload":"ZXhhbXBsZQ==","contentTopic":"string","version":0,"timestamp":0}'
When querying messages I get 404 with not subscribed to topic
curl -vv -X GET "http://127.0.0.1:63970/relay/v1/messages/%2Fwaku%2F2%2Fdefault-waku%2Fproto" -H "accept: application/json" 
If I use nwaku instead of …
```

fix: decode url param in relay rest API

---

waku/v2/discv5/discover.go
waku/v2/discv5/discover_test.go

feat: discv5 filter out nodes that have empty waku capabilities

---

cmd/waku/server/rest/relay.go
cmd/waku/server/rest/relay_test.go

chore: add unit tests for autosharding relay REST API

---

examples/basic2/main.go
examples/c-bindings/main.c
examples/chat2/flags.go
examples/rln/main.go
library/c/api.go
library/mobile/api.go
library/node.go
waku/v2/protocol/content_topic.go
waku/v2/protocol/envelope_test.go
waku/v2/protocol/relay/waku_relay_test.go
waku/v2/protocol/shard.go
waku/v2/protocol/topic_test.go

Allow application version to be string in contentTopic as per rfc 51 https://rfc.vac.dev/spec/51/#automatic-sharding
Note: rust-bindings will have to be updated accordingly. @richard-ramos

fix: content topic validation as per rfc 51

---

cmd/waku/server/rest/relay.go
cmd/waku/server/rpc/relay.go
waku/v2/protocol/relay/waku_relay.go

@fbarbu15 reported few issues he faced while testing RPC and REST API for relay with latest go-waku image.
These are fixes for some of the issues noticed.

fix : issues with get messages API

---

.github/workflows/lint_pr.yml

Adds this github action https://github.com/marketplace/actions/semantic-pull-request to ensure PRs follow the conventional commits spec https://www.conventionalcommits.org/en/v1.0.0/

chore: semantic PR linter

---

waku/v2/protocol/peer_exchange/enr_cache.go
waku/v2/protocol/peer_exchange/protocol.go

Removes some noise from the logs, by only adding a log when we discover a new peer

fix: noisy peer exchange log

---

flake.nix
waku/v2/protocol/pb/codec.go
waku/v2/protocol/pb/validation.go

Fixes an issue reported by @fbarbu15 in which the waku message content topic field was not being decoded correctly in the REST API

fix: WakuMessage json encoding

---

cmd/waku/flags.go
cmd/waku/main.go
cmd/waku/node.go
cmd/waku/options.go
cmd/waku/server/rest/utils_test.go
library/node.go
waku/persistence/postgres/postgres.go
waku/persistence/sqlite/sqlite.go
waku/persistence/utils/db.go
waku/v2/node/connectedness_test.go
waku/v2/node/wakunode2_test.go
waku/v2/protocol/store/utils_test.go
waku/v2/rendezvous/rendezvous_test.go

`VACUUM`, as described in https://github.com/waku-org/nwaku/pull/2165 is an operation that takes a substantial amount of time to be executed depending on the number of rows in the database. Based on the experience so far since the introduction of this flag, It's for the better to execute this command as an operation done via cron or manually, instead of having it be part of the code of waku.

chore: remove `--store-message-db-vacuum` 

---

waku/v2/protocol/rln/group_manager/dynamic/dynamic.go
waku/v2/protocol/rln/group_manager/dynamic/handler_test.go
waku/v2/protocol/rln/group_manager/dynamic/membership_fetcher_test.go
waku/v2/protocol/rln/group_manager/root_tracker.go
waku/v2/protocol/rln/group_manager/static/static.go
waku/v2/protocol/rln/onchain_test.go
waku/v2/protocol/rln/rln_relay_test.go
waku/v2/protocol/rln/waku_rln_relay.go

Panics if while retrieving the merkle root, there's a failure. Having an error in RLN at this stage will probably mean that we have an inconsistent state in the merkle tree, so it's better to stop the program execution
closes #738

fix: panic if it is not possible to obtain the merkle root

---

waku/v2/protocol/relay/validators.go

This PR addresses an issue in the WakuRelay's topic validation mechanism. Previously, if topicValidators were not set for a specific topic but defaultTopicValidators were provided, the logic incorrectly bypassed executing these default validators. This was due to the check being performed before merging the defaultTopicValidators. The proposed change ensures we correctly assess the combined list of validators after merging both topicValidators and defaultTopicValidators. This means that all validators will always be considered, regardless of whether specific topic validators are set.

fix: Execution logic for default topic validators in WakuRelay

---

cmd/waku/relay.go
cmd/waku/rlngenerate/command_rln.go
cmd/waku/rlngenerate/web3.go
cmd/waku/server/rpc/relay.go
logging/logging.go
waku/v2/protocol/filter/server.go
waku/v2/protocol/lightpush/waku_lightpush.go
waku/v2/protocol/relay/metrics.go
waku/v2/protocol/relay/waku_relay.go
waku/v2/protocol/relay/waku_relay_test.go
waku/v2/utils/logger.go

Adds a separate logging subsystem for relay/filter messages, to rely on https://github.com/ipfs/go-log#golog_log_level.
Also removes `logging.HexString` in favour of `logging.HexBytes`.

chore: add messages logging subsystem

---

cmd/waku/server/rest/filter.go
cmd/waku/server/rest/filter_cache.go
cmd/waku/server/rest/lightpush_rest.go
cmd/waku/server/rest/lightpush_rest_test.go
cmd/waku/server/rest/message.go
cmd/waku/server/rest/relay.go
cmd/waku/server/rest/relay_test.go
cmd/waku/server/rest/store.go
cmd/waku/server/rpc/utils.go
cmd/waku/server/utils.go

Previously, marshalling the protobuffer to json, ended up including a lot of fields that are not part of the rest api described in .yml files. With this PR, we use a struct `RestWakuMessage` which contains the fields described in the API

fix(rest): use custom struct for messages instead of protobuffer

---

cmd/waku/server/rest/store.go
cmd/waku/server/rpc/store.go
library/store.go
waku/v2/node/wakunode2.go
waku/v2/peermanager/peer_discovery.go
waku/v2/peermanager/peer_manager.go
waku/v2/peermanager/peer_manager_test.go
waku/v2/peermanager/peer_selection.go
waku/v2/peerstore/waku_peer_store.go
waku/v2/protocol/content_filter.go
waku/v2/protocol/filter/client.go
waku/v2/protocol/filter/filter_proto_ident_test.go
waku/v2/protocol/legacy_filter/waku_filter.go
waku/v2/protocol/lightpush/waku_lightpush.go
waku/v2/protocol/shard.go
waku/v2/protocol/store/waku_store_client.go
waku/v2/protocol/store/waku_store_protocol.go
waku/v2/protocol/store/waku_store_protocol_test.go
waku/v2/rendezvous/rendezvous.go
waku/v2/service/common_discovery_service.go

Store API changes to support auto-sharding as per #786

feat: update store client Query API for autosharding

---

cmd/waku/node.go
waku/v2/peermanager/peer_manager.go

When discv5 is enabled, build/waku command was panicking due to invalid memory reference.
@harsh-98 , this got introduced in #884 . 
Whenever we make changes to cmd related code, better to validate it by running a service node with options tht are affected.

fix: panic when discv5 is enabled while running service node

---

waku/persistence/utils/db.go

Allow using `postgres` in the db connection string to match nwaku. 
(`postgresql` and `postgres` are valid db url prefixes according to `libpq`)

fix: allow to use `postgres` in DB url

---

tests/string_generators_test.go
tests/utils.go
waku/v2/protocol/filter/filter_push_test.go
waku/v2/protocol/filter/filter_subscribe_test.go
waku/v2/protocol/filter/filter_test.go
waku/v2/protocol/filter/filter_unsubscribe_test.go

Description
Batch of tests for Waku Filter v2 - PUSH with valid payloads
Changes
Tests available to run:
cd go-waku/waku/v2/protocol/filter
go test

chore: filter v2 tests push valid payload

---

waku/v2/protocol/filter/filter_push_test.go
waku/v2/protocol/filter/filter_test.go

Changes
Adding more time to wait for a message sent during the test. Messages could be up to 1MB and it may take longer on slower computers to receive them.

test: extend timeout for single message

---

waku/v2/protocol/metadata/waku_metadata.go
waku/v2/protocol/metadata/waku_metadata_test.go

fix: do not start metadata protocol unless required

---

ci/Jenkinsfile.docker

Using custom registry for hosting Docker images: https://harbor.status.im
Images will be replicated from Harbor repository to Docker Hub

feat: setting image deployment to Harbor Registry

---

waku/v2/dnsdisc/enr.go

Add opt to allow custom resolver, use the dnsdisc.Resolver interface instead of the net.Resolver data type.
Related to: https://github.com/status-im/status-go/pull/4381

chore: allow custom resolver for dns discovery

---

waku/metrics/http.go
waku/v2/protocol/relay/waku_relay.go

gossipsub internally drops a message from being published to peers if it exceed maxMessageSize which is by default set to 1MB. This doesn't give a good dev ex as user of Waku relay assumes that message is successfully published even it is greater than msgSize. 
Similar observation is made in https://github.com/status-im/status-go/issues/4355
Hence, a size check is done before publishing the message to return error if the messageSize is greater than pubsub DefaultMaxMsgSize

fix: return error in relay publish if exceeding max-msg-size

---

waku/v2/protocol/filter/filter_subscribe_test.go
waku/v2/protocol/filter/filter_test.go
waku/v2/protocol/filter/filter_unsubscribe_test.go

Description
Batch of tests for Waku Filter v2 to improve coverage
Changes
Tests available to run:
cd go-waku/waku/v2/protocol/filter
go test

chore: filter v2 tests coverage improvement

---

.codeclimate.yml
waku/v2/dnsdisc/enr.go
waku/v2/dnsdisc/enr_test.go

The change add error handling based on this comment https://github.com/waku-org/go-waku/pull/930#discussion_r1407134171
~This seems a bit tedius to me and brings less value. How do you think?~

chore: error handling in params construction

---

waku/v2/node/wakunode2.go
waku/v2/protocol/store/waku_store_client.go
waku/v2/protocol/store/waku_store_protocol.go

This change is required to be able to override the default factory store

feat: make `criteriaFN` public

---

cmd/waku/server/rest/admin.go
cmd/waku/server/rest/admin_api.yaml
waku/v2/node/wakunode2.go

While debugging, felt the need for this change.
Fixes #830

feat: include pubsubTopics supported by peer in getPeers REST API 

---

waku/v2/protocol/rln/waku_rln_relay.go

If message timestamp is not set, then as part of appending RLN proof to the message, the timestamp is also set based on which the RLN proof is calculated.
Fixes #926 and not just REST API but for all API's.
cc @waku-org/nwaku-developers This would have to be addressed in nwaku REST API as well.

feat: fill msg timestamp while appending RLN proof it is not set

---

cmd/waku/server/rest/store.go
waku/v2/protocol/store/waku_store_client.go
waku/v2/protocol/store/waku_store_common.go
waku/v2/protocol/store/waku_store_protocol.go

While chatting with @igorsirotin, he pointed out the difference in behavior in storenode implementations between go-waku and nwaku. This PR fixes this difference

fix(store): set pagesize behavior match nwaku

---

waku/v2/peermanager/peer_manager.go

We were assuming that if a peer already existed on the store, it was already seen, regardless of the ENR being updated or not.

fix: take into account the ENR seq to determine if a peer is new or not

---

waku/v2/protocol/peer_exchange/enr_cache.go
waku/v2/protocol/peer_exchange/protocol.go
waku/v2/protocol/peer_exchange/shard_lru.go
waku/v2/protocol/peer_exchange/shard_lru_test.go

Add data structure for storing peers by cluster/index in peerExchange.  Related to https://github.com/waku-org/go-waku/issues/839
- Addition of node takes time complexity  of O(count of prev index+ new indexes).

refactor: shard LRU for storing peers by shard 

---

cmd/waku/node.go
cmd/waku/server/rest/admin.go
waku/v2/node/wakunode2.go

- Admin REST API to add peer was using default clusterID rather than node's configured clusterID.
- If clusterID is set to non-zero, do not subscribe to default pubsubTopic `/waku/2/default-waku/proto`

fix: use node's clusterId when adding peer from admin REST API & don't subscribe to default pubsub topic for non-zero clusterID

---

cmd/waku/server/rest/filter.go
cmd/waku/server/rest/filter_test.go
waku/v2/protocol/filter/common.go

Fixes #970 and #968 and also aligns with error mapping as per nwaku
Tested locally below scenarios:
-  ping without subscription returns 404 
- subscribe request with missing request-ID returns 400
- unsubscribe without content-topic returns 400

fix: return appropriate error code for filter subscribe ping

---

.github/workflows/ci.yml
examples/basic2/go.mod
examples/basic2/go.sum
examples/chat2/go.mod
examples/chat2/go.sum
examples/filter2/go.mod
examples/filter2/go.sum
examples/noise/go.mod
examples/noise/go.sum
examples/rln/go.mod
examples/rln/go.sum
flake.nix
go.mod
go.sum

RLN epoch was set to 10 secs which is not in compliant with TWN spec https://rfc.vac.dev/spec/64/#rln-parameters .
go-zerokit-rln was updated to set this epoch to 1 sec and hence the version is bumped in go-waku to use updated version of rln.

fix: use updated zerokit-rln with epoch as 1 sec as per TWN spec

---

waku/v2/peermanager/peer_manager.go

While running local go-waku node, had noticed that same peer was getting added again and again despite checks for duplicates and ENR updates.
Noticed that ENR update check was failing even if sequence number of ENR is not updated.

fix: ENR seq check to skip adding already existing peer

---

waku/v2/protocol/filter/filter_subscribe_test.go
waku/v2/protocol/filter/pb/validation.go

Changing this as per https://github.com/waku-org/nwaku/issues/2338

chore: increase maxContentFilter limit for Filter protocol to 100

---

waku/v2/node/wakunode2.go

Florin ran into an issue which has 2-fold solution. 
As per https://github.com/waku-org/go-waku/issues/988#issuecomment-1876810340 , the Filter-Subscribe REST API was timing out in node2 eventhough it is connected to node1(which has Filterv2 enabled).
But since node1's ENR is not settings Filter bit in Waku2 field, node2 doesn't consider node1 as filter node as it is only found via discovery.
Second problem is his request times-out because node2 goes into on-demand discovery and does till REST API times out.
This will have to improved for dev-ex, by having an internal timeout for on-demand discovery and responding back with error.

fix: use both filter and legacyFilter flags to determine if filter is enabled and set Waku2 ENR field

---

cmd/waku/flags.go
cmd/waku/main.go
cmd/waku/node.go
cmd/waku/options.go
waku/v2/node/wakunode2.go
waku/v2/node/wakuoptions.go
waku/v2/peermanager/connection_gater.go

Matches https://github.com/waku-org/nwaku/pull/2323

feat: parameterizable number of connections per IP

---

waku/v2/node/wakuoptions.go

Fixes all loggers to be set to log-level of the logger object passed. 
Also fixes logs in status-desktop for libp2p which are not printed with proper file name for log origin. 
As of now logs are printed as below
```
DEBUG[01-23|16:06:42.943|go.uber.org/zap/sugar.go:127]                                                   [Fx] SUPPLY    []upgrader.StreamMuxer
DEBUG[01-23|16:06:42.943|go.uber.org/zap/sugar.go:127]                                                   [Fx] SUPPLY    peer.ID
DEBUG[01-23|16:06:42.943|go.uber.org/zap/sugar.go:127]                                                   [Fx] PROVIDE   host.Host <= github.com/libp2p/go-libp2p/config.(*Config).addTransports.func2()
DEBUG[01-23|16:06:42.943|go.uber.org/zap/sugar.go:127]                                                   [Fx] …
```

chore: set log level for all loggers based on logger passed

---

waku/v2/protocol/rln/group_manager/dynamic/dynamic.go

Update lastProcessedBlock even if no RLN membership event is present or membership removed event is present.
This is an optimization to handle a scenario of not requiring to sync on restart from blocks which were already processed but not updated due to no events being processed.

fix: update lastProcessedBlock even if no RLN membership event is present

---

waku/v2/peermanager/peer_connector.go
waku/v2/peermanager/peer_discovery.go

Noticing sometimes on my status desktop that there are no peer connections.
Wanted to add these logs that would help debug situations where backoff is causing issues with connecting to peers.

chore: add logs for peer connection backoff

---

.github/workflows/ci.yml

Postgres or StoreNode is not used by status and go-waku is descoped for serviceNode.

chore: removing tests with postgres as it keeps failing in CI 

---

waku/v2/protocol/peer_exchange/client.go
waku/v2/protocol/peer_exchange/waku_peer_exchange_option.go
waku/v2/protocol/peer_exchange/waku_peer_exchange_test.go
waku/v2/protocol/shard.go

Addresses https://github.com/waku-org/go-waku/issues/839
Note: I have not added support to return peers matching more than 1 shard as that complicates the logic (of finding peer-exchange peers that match specific shards etc) and would rather be simpler if implemented at application level.

feat: peer exchange filter by shard

---

examples/chat2/chat.go
library/lightpush.go
waku/v2/protocol/lightpush/metrics.go
waku/v2/protocol/lightpush/waku_lightpush.go
waku/v2/protocol/lightpush/waku_lightpush_option.go
waku/v2/protocol/lightpush/waku_lightpush_option_test.go
waku/v2/protocol/lightpush/waku_lightpush_test.go

Adds an optional rate limit (that we should set in status-go).
Fixes https://github.com/waku-org/go-waku/issues/667

chore: add rate limiter option to lightpush

---

waku/v2/node/connectedness.go
waku/v2/node/connectedness_test.go
waku/v2/node/wakunode2.go
waku/v2/node/wakuoptions.go
waku/v2/node/wakuoptions_test.go
waku/v2/peermanager/peer_connector.go
waku/v2/peermanager/peer_manager.go
waku/v2/peermanager/topic_event_handler.go
waku/v2/peerstore/waku_peer_store.go
waku/v2/protocol/relay/config.go
waku/v2/protocol/relay/waku_relay.go
waku/v2/protocol/utils.go

Implements https://github.com/waku-org/go-waku/issues/1021

feat: topic health reporting

---

ci/Jenkinsfile.nix-flake

Related infra change:
- [`infra-ci#37c6ce47`](https://github.com/status-im/infra-ci/commit/37c6ce47) - nix-setup: upgrade from 2.14.1 to 2.19.2

chore: upgrade CI from Nix 2.14 to 2.19

---

waku/v2/discv5/discover.go
waku/v2/protocol/peer_exchange/protocol.go
waku/v2/protocol/peer_exchange/waku_peer_exchange_test.go

Adds an artificial delay to peer exchange (the same one used by discv5).
Might help with https://github.com/status-im/status-desktop/issues/13641#issuecomment-1954645291

chore: add artificial delay to peer-exchange

---

waku/v2/protocol/filter/filter_test.go
waku/v2/protocol/filter/options.go
waku/v2/protocol/filter/server.go
waku/v2/protocol/filter/subscribers_map.go
waku/v2/protocol/filter/subscribers_map_test.go

Filter subscribers need to ping at least once in the last 4:59m to keep their subscription alive (like in nwaku)

refactor: use ttl of 5m for subscriptions

---

waku/v2/protocol/peer_exchange/client.go
waku/v2/protocol/peer_exchange/metrics.go
waku/v2/protocol/peer_exchange/protocol.go
waku/v2/protocol/peer_exchange/waku_peer_exchange_option.go

Adds rate limit option to peer exchange
closes #1042

feat(peer-exchange): rate limit

---

waku/v2/node/connectedness_test.go
waku/v2/node/wakunode2.go
waku/v2/peermanager/peer_manager.go
waku/v2/peermanager/peer_manager_test.go
waku/v2/peermanager/topic_event_handler.go
waku/v2/protocol/lightpush/waku_lightpush_test.go
waku/v2/protocol/metadata/waku_metadata.go
waku/v2/protocol/metadata/waku_metadata_test.go
waku/v2/protocol/peer_exchange/waku_peer_exchange_test.go
waku/v2/protocol/shard.go
waku/v2/protocol/store/waku_store_client_test.go

As described here https://github.com/waku-org/nwaku/issues/2491 metadata protocol disconnects light clients.
With this change, instead of doing the metadata verification for all peers, it is done only for relay peers.

fix(metadata): only verify peer metadata on relay

---

waku/v2/peermanager/topic_event_handler.go

Only executes the shard mismatch verification if the metadata protocol was actually mounted
closes #1055

fix: verify if metadata exists before checking for shard mismatch

---

waku/v2/peermanager/service_slot_test.go

Fixing test related to service slot failing sometimes on race condition.  Reason:
2024-03-18T16:36:07.752+0800	ERROR	gowaku.host3.peer-manager	peermanager/peer_discovery.go:58	cannot do on demand discovery for non-waku protocol	{"protocol": "/test"}
2024-03-18T16:36:07.752+0800	ERROR	gowaku.host3.peer-manager	peermanager/peer_discovery.go:115	failed to discover and connect to peers	{"error": "cannot do on demand discovery for non-waku protocol"}
Use Waku protocol "/vac/waku/test/[version]" instead of "test/protocol".
```
2024-03-18T08:24:23.393Z	INFO	gowaku.host3.discv5	discv5/discover.go:193	Discovery V5: discoverable ENR 	{"enr": "enr:-KG4QCUJgO_m_1NB16nyXD1JoKPWSV8gyAKRcKAQC14OBRivHzGlEiphugbj5e9ajk6glsT0TlDwE0rhyfKD0twa-biGAY5QqWhegmlkgnY0gmlwhH8AAAGCcnOFAAEBAAGJc2VjcDI1NmsxoQIL5iPiznZ …
```

fix: service slot tests

---

waku/v2/peermanager/service_slot_test.go

Check for uniqueness was incorrectly done as comparison of non-serialized map elements.
Fetched peers map serialized before comparison.
```
2024-03-20T01:38:59.293Z	INFO	gowaku	peermanager/peer_manager.go:192	PeerManager init values	{"maxConnections": 10, "maxRelayPeers": 8, "outRelayPeersTarget": 10, "inRelayPeersTarget": -2, "maxPeers": 20}
2024-03-20T01:38:59.305Z	WARN	p2p-config	config/config.go:304	rcmgr limit conflicts with connmgr limit: conn manager high watermark limit: 192, exceeds the system connection limit of: 1
2024-03-20T01:38:59.310Z	INFO	gowaku.host1	peermanager/peer_manager.go:192	PeerManager init values	{"maxConnections": 10, "maxRelayPeers": 8, "outRelayPeersTarget": 10, "inRelayPeersTarget": -2, "maxPeers": 20}
2024-03-20T01:38:59.311Z	WARN	p2p-config …
```

fix: service slot  test failure - regression

---

waku/v2/discv5/discover.go
waku/v2/protocol/enr/localnode.go

While debugging a message reliability issue in status-go I noticed that the ENRs were lacking the UDP port
This was introduced in https://github.com/status-im/status-go/pull/4610, and in this PR Il update the UDP port used in the params with whatever value is obtained from ListenUDP

fix: handle discv5 udp port 0

---

waku/v2/peermanager/peer_manager.go

While debugging #1077 I noticed that the relay connectivity loop locks for reading the topicMutex. This means that while this lock is RLocked, it will not be possible to lock it for writing (which happens when we subscribe to topics).  Profiling this code, I saw that when this function attempts to discover new peers, it ends up locking the mutex for as long as there are not enough peers for a topic. Since discovering peers is a potentially long operation, I decided to run it into a separate goroutine to avoid having the topicsMutex locked longer than necessary. 
closes #1077

fix(peer-manager): discovering peers should not lock the peer manager

---

cmd/waku/server/rest/store.go
waku/v2/protocol/lightpush/waku_lightpush.go
waku/v2/protocol/store/waku_store_client.go
waku/v2/protocol/store/waku_store_common.go
waku/v2/protocol/store/waku_store_protocol.go

Sets the behavior for store queries in REST to be similar to nwaku, in which if no peer is specified, and the wakunode is a store node, then it will query itself.
In addition to that, I noticed that the store protocol was registering itself to be used in the ENR when instantiating `WakuStore`, and this is wrong because instantiating a `WakuStore` does not mean that the node itself will be a store node (it can be only a client), so I moved that part of the code to the `Start` function.
closes #1087

fix(rest/store): allow local queries

---

Makefile

The `GOBIN` environment variable is a reserved name. The conditional variable assignment operator would not set the path to the `go` command if `GOBIN` is set in the parent environment.
```
GOBIN
The directory where 'go install' will install a command.
```
from `go help environment`.
- Rename the environment variable.
- Run the `make` command with and without setting the `GOBIN` environment variable.

chore: rename `GOBIN` as `GOCMD`

---

go.sum
waku/v2/node/wakuoptions.go
waku/v2/peermanager/fastest_peer_selector.go
waku/v2/peermanager/fastest_peer_selector_test.go
waku/v2/peermanager/peer_manager.go
waku/v2/peermanager/peer_selection.go
waku/v2/protocol/lightpush/waku_lightpush_test.go

Cache that contains the ping times for peers, for reusing the value instead of pinging a peer each time you want to select the fastest peer.  Ping times are verified every 10 seconds.

feat: ping cache

---

examples/filter2/main.go
waku/v2/node/wakunode2.go
waku/v2/node/wakuoptions.go
waku/v2/protocol/lightpush/pb/validation.go
waku/v2/protocol/lightpush/waku_lightpush.go

This PR adds missing Lightpush options to `withLightpush()` builder function. It also fixes a missing `requestId` issue which resulted in rate limitting errors showing up as `missing RequestId field` error.
It also enhances `fitler2` example to setup lightpush on the full node with rate limit to allow for some basic experimentation.

fix(lightpush): return non-empty reqId and add LP opts to builder

---

.dockerignore
flake.nix

Fixes this error:
```
22:55:49   > [builder 4/4] RUN make -j$(nproc) build:
22:55:49  2.885 go: downloading github.com/syndtr/goleveldb v1.0.1-0.20220614013038-64ee5596c38a
22:55:49  2.897 go: downloading github.com/quic-go/qtls-go1-20 v0.3.4
22:55:49  2.900 go: downloading github.com/shirou/gopsutil v3.21.4-0.20210419000835-c7a38de76ee5+incompatible
22:55:49  2.907 go: downloading github.com/btcsuite/btcutil v0.0.0-20190425235716-9e5f4b9a998d
22:55:49  2.931 go: downloading github.com/golang/snappy v0.0.4
22:55:49  2.962 go: downloading github.com/tklauser/go-sysconf v0.3.5
22:55:49  2.991 go: downloading github.com/tklauser/numcpus v0.2.2
22:55:49  6.162 waku/v2/protocol/filter/test_utils.go:16:2: no required module provides package github.com/waku-org/go-waku/tests; to add it:
22:55:49 …
```

fix: dockerfile

---

tests/utils.go
waku/v2/api/filter.go
waku/v2/api/filter_test.go
waku/v2/peermanager/peer_manager.go
waku/v2/peermanager/peer_manager_test.go
waku/v2/peermanager/peer_selection.go
waku/v2/peermanager/service_slot.go
waku/v2/peermanager/service_slot_test.go
waku/v2/protocol/filter/client.go
waku/v2/protocol/filter/filter_health_check.go
waku/v2/protocol/filter/filter_subscribe_test.go
waku/v2/protocol/filter/filter_test.go
waku/v2/protocol/filter/filter_unsubscribe_test.go
waku/v2/protocol/filter/options.go
waku/v2/protocol/filter/test_utils.go
waku/v2/protocol/subscription/subscription_details.go
waku/v2/protocol/subscription/subscriptions_map.go

Implementing #1099 , realized that there are some issues wrt approach taken in https://github.com/waku-org/go-waku/pull/1048
Following are the issues being addressed/to be addressed:
1. For each subscription towards same peer, pings are sent which is unnecessary traffic periodically
2. There is no check that if a Filter ping fails , a susbcribe is done what if it already chooses another peer for which we have subscription against? (tracked https://github.com/waku-org/go-waku/issues/1104)
Taking an approach to not send an actual ping via Filter Subscription Ping API, rather check status of last ping. And trying to no refactor code much, so that we can check results faster. 
Note: Tests are still pending.
Approach/Impementation Details:
- Have a separate go-routine that collates unique …

feat: changes for optimizing filter ping

---

cmd/waku/node.go
waku/v2/node/connectedness_test.go
waku/v2/node/wakunode2.go
waku/v2/peermanager/peer_manager.go
waku/v2/peermanager/peer_selection.go

When rebasing from develop onto https://github.com/status-im/status-go/pull/4665 , had noticed that when i run Filter test in status-go, there is a crash due to hitting a scenario where peer is already in peerStore and again being added via discovery but doesn't have ENR. 
The log statement is causing a crash.
following is the backtrace
```
signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1013cb770]
goroutine 391 [running]:
github.com/ethereum/go-ethereum/p2p/enode.(*Node).Seq(0x14000923230?)
/Users/prem/Code/bkp/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode/node.go:89
github.com/waku-org/go-waku/waku/v2/peermanager.(*PeerManager).AddDiscoveredPeer(0x140000da210, {0x4, {{0x14000923230, 0x27}, {0x140002cb780, 0x3, 0x4}}, 0x0, {0x140008d2c40, 0x1, ...}}, ...) …
```

fix: crash noticed while adding existing peer that doesn't have an ENR

---

waku/v2/peermanager/peer_manager.go
waku/v2/protocol/relay/waku_relay.go

While testing https://github.com/status-im/status-go/pull/5350 after enabling peerExchangeClient, had noticed a good number of peer connection failures happen because of peer addresses expiring. 
If a peer is discovered dynamically, its address TTL i set to default value which is 1 hour. 
Eventhough the peer is discovered again later, only the ENR is updated in case of a change. This results in addresses being expired and hence failing to connect to these peers with error "no addresses".
`ERROR[06-14|15:41:07.989|github.com/waku-org/go-waku/waku/v2/protocol/filter/client.go:405]                          Failed to subscribe                      pubSubTopic=/waku/2/rs/16/32 contentTopics=[/waku/1/0x7135123e/rfc26] error="failed to dial: failed to dial …

fix: add peer addresses on expiry if peer is discovered again

---

Makefile
waku/v2/discv5/discover_test.go
waku/v2/node/localnode.go
waku/v2/peermanager/peer_manager_test.go
waku/v2/protocol/enr/enr.go
waku/v2/protocol/enr/enr_test.go
waku/v2/protocol/enr/localnode.go
waku/v2/service/common_discovery_service.go

The reason why i removed the condition of checking for the length of the multiaddress is that we can just let the error handling determine whether writing to the enr was succesful or not.

fix: do not write tcp port 0 and remove 100 chars length limit for multiaddresses

---

waku/v2/node/address_test.go
waku/v2/node/localnode.go
waku/v2/protocol/enr/localnode.go

This is so the circuit relay `multiaddrs` only use IP and not the long URLs like those used on the fleet.
This has the drawback that if the domain name is updated to point to a different IP, the IP address stored in the `multiaddr` field will no longer be valid, but I think this is okay, since ENRs are not the ideal place for storing circuit relay addresses (we should use rendezvous instead), and it's done only in an attempt to provide a way for peers to announce themselves.

fix: use IP addresses instead of dns to store multiaddresses

---

waku/v2/api/filter.go
waku/v2/api/filter_test.go
waku/v2/node/wakunode2.go
waku/v2/node/wakuoptions.go
waku/v2/onlinechecker/online.go
waku/v2/peermanager/peer_connector.go
waku/v2/peermanager/peer_manager_test.go
waku/v2/protocol/filter/client.go
waku/v2/protocol/filter/test_utils.go
waku/v2/protocol/peer_exchange/waku_peer_exchange_test.go

Allows consumers of the library to setup the node online/offline state

feat: online checker

---

logging/logging.go
waku/v2/node/wakunode2.go
waku/v2/node/wakuoptions.go
waku/v2/peermanager/peer_connector.go
waku/v2/peermanager/peer_discovery.go
waku/v2/peermanager/peer_manager.go
waku/v2/peermanager/peer_manager_test.go
waku/v2/peermanager/topic_event_handler.go
waku/v2/peermanager/topic_event_handler_test.go
waku/v2/protocol/filter/test_utils.go
waku/v2/protocol/legacy_store/waku_store_client_test.go
waku/v2/protocol/lightpush/waku_lightpush_test.go
waku/v2/protocol/metadata/waku_metadata.go
waku/v2/protocol/peer_exchange/waku_peer_exchange_test.go
waku/v2/protocol/store/client_test.go

Also start refactor to work with lightMode.
Complete refactor will happen in separate PR to avoid blocking the changes for relay.
Addresses https://github.com/waku-org/go-waku/issues/1132

feat: modify peer-manager to consider relay target peers 

---

waku/v2/node/wakunode2.go
waku/v2/protocol/peer_exchange/enr_cache.go
waku/v2/protocol/peer_exchange/protocol.go
waku/v2/protocol/peer_exchange/waku_peer_exchange_test.go

If a clusterID is specified, the peers stored in the cache will only store peers that match the specified cluster-id based on the shards from their ENR.
See: https://github.com/waku-org/go-waku/pull/1130 for discussion about why this change is necessary

feat: filter peers stored in cache by cluster-id in peer-exchange

---

waku/v2/node/localnode.go
waku/v2/protocol/enr/enr.go

- WS / WSS addresses are not taken into account for circuit relay
- Allows storing arbitrary data in the `multiaddrs` ENR key. If a value is not recognized, it's ignored

fix: ignore ws from circuit relay addresses, and allow non multiaddresses in `multiaddrs` ENR key

---

examples/basic-light-client/go.mod
examples/basic-light-client/go.sum
examples/basic-relay/go.mod
examples/basic-relay/go.sum
examples/chat2/go.mod
examples/chat2/go.sum
examples/filter2/go.mod
examples/filter2/go.sum
examples/noise/go.mod
examples/noise/go.sum
examples/rln/go.mod
examples/rln/go.sum
flake.nix
go.mod
go.sum
waku/v2/node/connectedness_test.go
waku/v2/node/wakunode2.go
waku/v2/peermanager/peer_manager.go
waku/v2/peermanager/peer_manager_test.go
waku/v2/peermanager/topic_event_handler_test.go
waku/v2/protocol/filter/test_utils.go
waku/v2/protocol/legacy_store/waku_store_client_test.go
waku/v2/protocol/lightpush/waku_lightpush_test.go
waku/v2/protocol/peer_exchange/waku_peer_exchange_test.go
waku/v2/protocol/store/client_test.go

Fixes #1131
I could not figure out the logic behind how `gs.mesh` is populated in go-lib2p2-pubsub, so in the meantime I disabled the test that check for connection changes

feat: use mesh peers instead of all peers for determining topic health

---

waku/v2/protocol/metadata/waku_metadata.go
waku/v2/protocol/metadata/waku_metadata_test.go

Similar to https://github.com/waku-org/nwaku/pull/2533 in nwaku. 
When a lightnode connects its shards info will not be sent via metadata, which will cause a relay node to disconnect it. 
Had noticed this behaviour while trying to connect from status-desktop lightClient to another status desktop in relay. 
this fix prevents that disconnection from happening.

fix: for light node do not check for matching shards but only clusterID

---

waku/v2/protocol/metadata/waku_metadata.go

Fix to take care of  intermittent failures in CI as in https://ci.status.im/blue/organizations/jenkins/status-go%2Fprs%2Ftests/detail/PR-5474/23/tests.
Consider chekcing for lightClient only if metadata request doesn't have shards filled in.

fix: check for lightclient only if req doesn't contain shards

---

waku/v2/node/localnode.go
waku/v2/node/wakunode2.go
waku/v2/node/wakuoptions.go
waku/v2/protocol/lightpush/waku_lightpush.go
waku/v2/protocol/metadata/waku_metadata.go

go-waku has the issue of disconnecting lightClients that don't provide shard info in metadata. This has been fixed in https://github.com/waku-org/go-waku/pull/1154 , but since it would take time for this change to propagate into the network of status desktop instances already running it is causing issues for lightClients to connect to existing nodes. 
e.g as explained here https://discord.com/channels/1110799176264056863/1261332218991738941
In order to mitigate this issue, this Pr would allow lightClients to set shards in their ENR which would in-turn be used in metadata exchange. Note that these changes are to be reverted once community sharding is implemented in status.

chore: allow setting enr shards for lightclient

---

waku/v2/protocol/filter/client.go
waku/v2/protocol/lightpush/waku_lightpush.go
waku/v2/protocol/lightpush/waku_lightpush_option.go
waku/v2/protocol/subscription/subscriptions_map.go
waku/v2/protocol/subscription/subscriptions_map_test.go

some error handling for lightClients

feat: lightclient err handling

---

waku/v2/protocol/filter/client.go
waku/v2/protocol/filter/server.go
waku/v2/protocol/legacy_store/waku_store_client.go
waku/v2/protocol/lightpush/waku_lightpush.go
waku/v2/protocol/metadata/waku_metadata.go
waku/v2/protocol/peer_exchange/client.go
waku/v2/protocol/store/client.go

Connection failures  are recorded only when attempted from peerManager or by invoking connect call. But all the req/resp protocols open streams which internally does a dial if there is no existing connection to the peer. If this dial fails, it is not recorded as a connection error.
Since connection errors recorded in peerStore are being used to report to telemetry, these would also have to be recorded as connection errors.
cc @adklempner

fix: record connection failures when stream opening fails for any protocol

---

waku/v2/api/filter.go
waku/v2/protocol/filter/filter_health_check.go

While going through filter ping code, had noticed that 
- ping timeout was set to PingInterval which is 1 minute and is too large to identify failures in case peer is down or network disconnected etc. So, reducing it to 5 seconds to catch errors faster
-  aligning with rfc https://github.com/waku-org/specs/blob/master/standards/application/req-res-reliability.md#regular-pings 
> -  added a second ping in case of failure before we give-up and move subscriptions to another peer. 
> This is as per  , and this has been implemented in js-waku as well.
> - Perform filter pings only when we are online

fix: filter ping timeout and retry in case of failure

---

waku/v2/node/wakunode2.go
waku/v2/protocol/filter/client.go

Noticed a possible race condition that can happen due to error-handling done for Filter where-in susbcribe request was sent to peer and before subscription was added, peer pushed a message and can lead to unsubscribe due to additional error handling added. 
It is a corner scenario but pretty much possible.

chore: method to disconnect all peers and not notify

---

waku/v2/peermanager/peer_manager.go

While debugging connectivity issue, i had noticed that we are relying on only meshPeers and comparing it to relay out peers target in order to establish more connections. Since gossipSubMesh max would only be 8 and we would try to establish out connections always even if we reach relay outPeersTarget which is set to 80 for status.
Changing the logic to check with total pubsubTopic peerCounts and also the meshPeerCount.

fix: use total peers for pubsubTopic as out peers target

---

waku/v2/protocol/filter/client.go
waku/v2/protocol/lightpush/waku_lightpush.go

Noticed that since we use 2 peers to subscribe for a filter and each subscription request it sent in sequence which causes delay in case first one times-out due to unreachability of peer. 
@jm-clius thanks for hint yesterday about parallel subscriptions that made me review this part of the code.

fix: parallelize filter subs to different peers

---

ci/Jenkinsfile.nix-flake
default.nix
flake.nix

Bit of a cleanup to make it more readable and also fix building of libraries.
Moving the actual build to `default.nix` makes `flake.nix` more readable.

chore(nix): refactor, fix library packages

---

docs/api/filter.md
docs/operators/how-to/configure-store.md
examples/android-kotlin/app/src/main/java/com/example/waku/MainActivity.kt
examples/c-bindings/main.c
examples/chat2/README.md
examples/waku-csharp/waku-csharp/Program.cs
library/c/README.md
waku/v2/node/address_test.go
waku/v2/protocol/enr/enr_test.go

Use of `statusim.net` domain been deprecated since March: https://github.com/status-im/infra-shards/commit/7df38c14

fix: replace references to old statusim.net domain

---

waku/v2/node/address_test.go
waku/v2/node/localnode.go
waku/v2/protocol/metadata/waku_metadata.go

Fixes this issue found by @mprakhov 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x1019b894c]
goroutine 143103 [running]:
github.com/waku-org/go-waku/waku/v2/protocol/metadata.(WakuMetadata).DisconnectPeerOnShardMismatch(0x14011434e70, {0x103c14a10?, 0x1400c7fd810?}, {0x14001d81f50, 0x27})
/Users/mprakhov/Work/status/status-desktop/vendor/status-go/vendor/github.com/waku-org/go-waku/waku/v2/protocol/metadata/waku_metadata.go:338 +0x24c
github.com/waku-org/go-waku/waku/v2/peermanager.(PeerManager).handlerPeerTopicEvent(0x1400b855380, {{0x1401e029940, 0x10}, {0x14001d81f50, 0x27}, 0x0})
/Users/mprakhov/Work/status/status-desktop/vendor/status-go/vendor/github.com/waku-org/go-waku/waku/v2/peermanager/ …
```

fix: handle scenario where the node's ENR has no shard (due to shard update)

---

default.nix
examples/basic-light-client/go.mod
examples/basic-light-client/go.sum
examples/basic-relay/go.mod
examples/basic-relay/go.sum
examples/chat2/go.mod
examples/chat2/go.sum
examples/filter2/go.mod
examples/filter2/go.sum
examples/noise/go.mod
examples/noise/go.sum
examples/rln/go.mod
examples/rln/go.sum
flake.nix
go.mod
go.sum
tests/utils.go
waku/v2/api/filter/filter_manager.go
waku/v2/api/filter/filter_test.go
waku/v2/protocol/filter/filter_ping_test.go
waku/v2/protocol/filter/filter_proto_ident_test.go
waku/v2/protocol/filter/filter_subscribe_test.go
waku/v2/protocol/filter/filter_test.go
waku/v2/protocol/filter/test_utils.go

chore: move filter manager from status-go to go-waku

---

.github/workflows/ci.yml
waku/v2/peermanager/peer_manager.go

While dogfooding status desktop by disconnected network, had noticed that relay mode crashed with below backtrace
```
panic: runtime error: slice bounds out of range [:-7]
goroutine 550 [running]:
github.com/waku-org/go-waku/waku/v2/peermanager.(*PeerManager).ensureMinRelayConnsPerTopic(0x240014f8540)
/Users/prem/Code/status-desktop/vendor/status-go/vendor/github.com/waku-org/go-waku/waku/v2/peermanager/peer_manager.go:337 +0x5c8
github.com/waku-org/go-waku/waku/v2/peermanager.(*PeerManager).connectToPeers(0x240014f8540)
/Users/prem/Code/status-desktop/vendor/status-go/vendor/github.com/waku-org/go-waku/waku/v2/peermanager/peer_manager.go:348 +0x2c
github.com/waku-org/go-waku/waku/v2/peermanager.(*PeerManager).connectivityLoop(0x0?, {0x10fdb03c8, 0x24000117720}) …
```

fix: use corrected connected peer count and add check to avoid crash

---

waku/v2/api/publish/message_check.go
waku/v2/api/publish/message_check_test.go

Move outgoing message check logic from status-go to go-waku

chore: move outgoing message check from status-go to go-waku

---

waku/v2/api/publish/message_queue.go
waku/v2/api/publish/message_queue_test.go

@igor-sirotin reported the following error:
panic: send on closed channel
```
goroutine 228896 [running]:
github.com/waku-org/go-waku/waku/v2/api/publish.(*MessageQueue).Push(...)
/Users/igorsirotin/Repositories/Status/status-go/vendor/github.com/waku-org/go-waku/waku/v2/api/publish/message_queue.go:131
github.com/status-im/status-go/wakuv2.(*Waku).Send(0x14002e9cf00, {0x14000bb8400?, 0xa?}, 0x1400347a000?, 0x107a22d50)
/Users/igorsirotin/Repositories/Status/status-go/wakuv2/message_publishing.go:56 +0x140
github.com/status-im/status-go/wakuv2.(*PublicWakuAPI).Post(0x14006e4a3f0, {0x14001258f00?, 0x84?}, {{0x14001259100, 0x40}, {0x0, 0x0, 0x0}, {0x14001258f00, 0x40}, ...})
/Users/igorsirotin/Repositories/Status/status-go/wakuv2/api.go:259 +0x568
```
Since this is happening because the …

fix: keep channels open

---

waku/v2/api/publish/message_check.go
waku/v2/api/publish/message_check_test.go
waku/v2/api/publish/message_sender.go
waku/v2/api/publish/message_sender_test.go
waku/v2/api/publish/rate_limiting.go

Fix https://github.com/waku-org/go-waku/issues/1181
API usage in status-go: https://github.com/status-im/status-go/pull/5676

chore: refactor sender api

---

waku/v2/api/missing/missing_messages.go
waku/v2/api/publish/message_check.go

Otherwise it can request too many records and add too much load to the storenodes

chore: limit the maximum number of message hashes to request per query

---

.gitignore
logging/logging.go
waku/v2/peermanager/peer_connector.go

chore: use utc time in logs to avoid user location getting disclosed

---

waku/v2/protocol/relay/waku_relay.go

This panic was randomly appearing in `TestPostToCommunityChat`:
```nim
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x11d7d31]
goroutine 1336997 [running]:
github.com/libp2p/go-libp2p-pubsub.(*Subscription).Topic(...)
/home/jenkins/workspace/status-go/tests-nightly/vendor/github.com/libp2p/go-libp2p-pubsub/subscription.go:21
github.com/waku-org/go-waku/waku/v2/protocol/relay.(*WakuRelay).unsubscribeFromPubsubTopic(0xc049a84200, 0xc06af0f280)
/home/jenkins/workspace/status-go/tests-nightly/vendor/github.com/waku-org/go-waku/waku/v2/protocol/relay/waku_relay.go:506 +0x31
github.com/waku-org/go-waku/waku/v2/protocol/relay.(*WakuRelay).Unsubscribe(0xc049a84200, {0xc02f751e50?, 0x2f9528a?}, {{0xc02b114060?, …
```

fix: flaky panic on relay unsubscribe

---

waku/v2/api/common/utils.go
waku/v2/api/missing/missing_messages.go
waku/v2/api/missing/options.go
waku/v2/api/publish/message_check.go

Hash query may take too long, set the timeout to 30s to raise alert for any longer queries.
closes https://github.com/waku-org/go-waku/issues/1189

fix: set default store hash query timeout to 30s

---

waku/v2/peermanager/peer_manager.go
waku/v2/protocol/relay/waku_relay.go

Fixes https://github.com/status-im/status-go/issues/5759
More details in the issue comments.
It's possible that those functions are called with such parameters that causes panics.
While we should probably find the root cause and fix it, I'd like to prevent panics in the first place.

fix: prevent panics in peermanager and WakuRelay

---

cmd/waku/server/rest/lightpush_rest_test.go
cmd/waku/server/rest/relay_test.go
waku/v2/api/publish/message_sender_test.go
waku/v2/node/wakunode2_test.go
waku/v2/protocol/filter/filter_test.go
waku/v2/protocol/lightpush/waku_lightpush_test.go
waku/v2/protocol/relay/waku_relay.go
waku/v2/protocol/relay/waku_relay_test.go

Relates to: https://github.com/waku-org/go-waku/issues/1207

fix: check subscription when relay publish message

---

waku/v2/node/keepalive.go

https://github.com/waku-org/go-waku/pull/1214 for 2.30.x branch

fix: use correct ticker for all peers ping

---

waku/v2/api/publish/message_queue.go

Required to fix: https://github.com/status-im/status-mobile/issues/21174

fix: make the envelope priority queue safe for concurrent access

---

ci/Jenkinsfile.docker

This PR updates the build stage which builds the Docker Image to use `GIT_REF` when its set.
This ensures that when we perform a parameterised build from Jenkins we actually get a docker image from the branch or commit we set in `GIT_REF`

ci: use GIT_REF for building docker image when set

---

waku/v2/node/wakunode2.go
waku/v2/node/wakuoptions.go
waku/v2/protocol/store/client.go
waku/v2/protocol/store/client_test.go
waku/v2/protocol/store/options.go
waku/v2/protocol/store/result.go

Part of the refactoring for the storenode cycle. This will rate limit the store queries to a max of 8 queries per second per peerID. (This is the value used in staging). It's possible to skip this rate limit via options. 
In addition to that while debugging an issue with the storenode message counter, i found that not being able to pass options to `Next` to be somewhat limiting, specially if you want to change the requestID to some deterministic value, hence i modified it to pass options.

feat: ratelimit store queries and add options to Next

---

waku/v2/api/filter/filter.go
waku/v2/api/filter/filter_manager.go
waku/v2/api/filter/filter_test.go

The fix made in release branch to update filter batch duration ticker to 300ms was not propagated correctly in the code that is moved to go-waku. 
this PR addresses the gaps in the fix propagation.

fix: filter batch duration opt was not propagated correctly

---

waku/v2/node/wakunode2.go
waku/v2/peermanager/peer_connector.go
waku/v2/peermanager/peer_manager.go
waku/v2/peermanager/peer_manager_test.go
waku/v2/protocol/filter/client.go
waku/v2/protocol/filter/server.go
waku/v2/protocol/legacy_store/waku_store_client.go
waku/v2/protocol/lightpush/waku_lightpush.go
waku/v2/protocol/peer_exchange/client.go
waku/v2/protocol/store/client.go
waku/v2/utils/peer.go

Upon error dialing in `PeerConnectionStrategy.dialPeer` or `WakuNode.connect`, emit a `DialError` event. This allows consumers of `go-waku` to subscribe to a channel which outputs the dial errors as they occur.
- Create `DialError` interface in utils
- Add an event emitter for `DialError` events to `PeerConnectionStrategy` (created in `Start()`, closed in `Stop()`)
- Add a function `HandleDialError` to `PeerConnectionStrategy` that:
- runs existing logic on dial failure (add backoff, add to connection failures in waku peer store)
- emit a `DialError` event using the ID of the peer and the returned error message from `c.host.Connect(ctx, pi)`
- use above function in `PeerConnectionStrategy.dialPeer` and `WakuNode.connect` when an error is returned by `host.Connect`

feat: emit an event in EventBus upon dial error

---

waku/v2/api/filter/filter.go
waku/v2/peermanager/fastest_peer_selector.go
waku/v2/peermanager/fastest_peer_selector_test.go
waku/v2/peermanager/peer_manager.go
waku/v2/peermanager/peer_manager_test.go
waku/v2/peermanager/peer_selection.go
waku/v2/peermanager/service_slot_test.go
waku/v2/utils/peer.go

Fixes https://github.com/status-im/status-go/issues/5679 where due to DNS failure,  filter subscribe loop is going into infinite loop leading to log flooding.

fix: simple backoff strategy after 3 subscribe failures

---

logging/logging.go
waku/v2/api/history/cycle.go
waku/v2/api/history/emitters.go
waku/v2/api/history/emitters_test.go
waku/v2/api/history/history.go
waku/v2/api/history/history_test.go
waku/v2/api/history/sort.go
waku/v2/api/missing/missing_messages.go
waku/v2/api/publish/message_check.go
waku/v2/api/publish/message_check_test.go
waku/v2/api/publish/message_sender.go
waku/v2/protocol/store/client.go
waku/v2/protocol/store/client_test.go
waku/v2/protocol/store/options.go
waku/v2/protocol/store/result.go

This PR contains the storenode cycle code from status-go.
I tried to simplify it a bit but most of the heavy refactoring should be done on a separate PR since this one is already complex enough.
@plopezlpz, @kaichaosun @igor-sirotin @chaitanyaprem:
I'm still working on the unit tests, but so far, while testing https://github.com/status-im/status-go/pull/5857 with Desktop, it looks promising. Reviews are appreciated!

feat: storenode cycle

---

waku/v2/api/common/result.go
waku/v2/api/missing/default_requestor.go
waku/v2/api/missing/missing_messages.go
waku/v2/api/publish/default_publisher.go
waku/v2/api/publish/default_verifier.go
waku/v2/api/publish/message_check.go
waku/v2/api/publish/message_sender.go
waku/v2/api/publish/message_sender_test.go

Since the integration with nwaku is being done thru status-go, I did a refactor over part of the `api` package so status-go can implement some interfaces that would let it invoke nwaku's bindings instead of using go-waku directly. 
To make the change transparent for status-go while we continue using go-waku, some of the code I extracted is provided as a default implementation.
cc: @gabrielmer @Ivansete-status

refactor: decouple API from go-waku

---

waku/v2/api/common/pinger.go

This would allow replacing the Ping function by a nim-libp2p implementation in status-go + nwaku.
A default implementation is also provided to be used in status-go + gowaku
cc: @gabrielmer  @Ivansete-status

refactor: extract ping interface

---

waku/v2/api/common/storenode_requestor.go
waku/v2/api/history/cycle.go
waku/v2/api/history/history.go
waku/v2/api/history/history_test.go
waku/v2/api/missing/default_requestor.go
waku/v2/api/missing/missing_messages.go
waku/v2/protocol/store/client.go

To allow more flexibility at the moment of doing queries, instead of having custom functions that receive N different combination of parameters to do a store query, we use instead a single function which receives instead a StoreQueryRequest protobuffer
The json representation of the StoreQueryRequest matches what is used in libwaku, and since protobuffers in nwaku and go-waku are the same (and are supposed to be backward compatible), we can safely use them. It has the side effect of making the API simpler too
cc: @gabrielmer, @Ivansete-status

refactor: use protobuffer for API storenode queries

---

waku/v2/api/filter/filter_manager.go
waku/v2/peermanager/peer_manager.go

While debugging filter issue, noticed that filter stats are mismatched because once a filter is removed it is still left in filtersubscriptions list in filterManager causing logs to be inconsistent. 
Also added a minor bad peer removal functionality for light nodes based on dial error count. This may help improve lightnode connectivity and reduce failures.
Logic is simple:
1. Consider a peer as bad-peer if its dial error count is more than 3. 
2. Keep checking for such bad peers and remove them every 1 minute.

fix: filter stats mismatch and add bad peer check for light mode

---

cmd/waku/node.go
waku/v2/node/wakunode2.go

go-waku `waku` command did not setup the list of shards on the ENR when relay was disabled. This ended up causing the node to not be able to connect due to the ENR not containing any shard. This change sets the list of shards regardless of relay being enabled or not
Fixes: https://github.com/waku-org/go-waku/issues/1255

fix: setup shards

---

waku/v2/api/history/history.go

Matches https://github.com/status-im/status-go/pull/6115

feat: limit api store queries to 24h

---

waku/v2/utils/crypto.go

Use `github.com/decred/dcrd/dcrec/secp256k1/v4` directly rather than `github.com/btcsuite/btcd/btcec/v2` which is just a wrapper around the underlying decred library. Inspired by ethereum/go-ethereum#30595
`github.com/btcsuite/btcd/btcec/v2` has a very annoying breaking change when upgrading from v2.3.3 to v2.3.4. The easiest way to work around this is to remove the wrapper.

chore: use decred secp256k1 directly

---

waku/v2/api/publish/message_sender.go
waku/v2/api/publish/message_sender_test.go

Adds an option when creating message sender to emit an event each time a message is sent.
Added a new unit test and tested locally in status-go via this PR https://github.com/status-im/status-go/pull/6157

feat: option to emit event to bus upon message sent

---

waku/v2/api/filter/filter_manager.go
waku/v2/api/missing/missing_messages.go
waku/v2/peermanager/peer_manager.go
waku/v2/protocol/filter/client.go
waku/v2/protocol/filter/filter_health_check.go
waku/v2/protocol/lightpush/waku_lightpush.go

Bunch of fixes and changes that help with offline state.
Being dogfooded https://github.com/status-im/status-mobile/issues/21172 for various network disconnection/switch scenarios.

fix:  use bad peer removal logic only for lightpush and filter and option to restart missing message verifier

---

waku/v2/api/publish/message_sender.go
waku/v2/protocol/filter/options.go

have better defaults for send/recv rate-limits to accomodate status use-case
default rate-limits set for publishing and filter client receiving is not sufficient for status and is causing message reliability issues like https://github.com/status-im/status-mobile/pull/21809#issuecomment-2539022490.
- increase receive rate-limit to match ~1000/min
- increase publish rate-limit to 5 per second
note that i have given higher bursts so that there is room for occasional bursts.

fix: have better defaults for send/recv rate-limits 

---

waku/v2/api/missing/missing_messages.go

this is a fix to update context for criteria in missing msg verifier after it is restarted. 
otherwise when state changes, it still uses old context causing fetches to get skipped.

fix: update criteria context on missing msg verifier start

---

waku/v2/api/filter/filter_manager.go
waku/v2/api/filter/filter_test.go
waku/v2/protocol/filter/client.go

If there is a network type change i.e from wifi to 4G even if it involves an intermediary transition to offline, then unsubscribe and resubscribe all filters. 
This is to avoid filter-push issue noticed as per https://discord.com/channels/1110799176264056863/1111541184490393691/1318842541436829717.

fix: filter network change

---

cmd/waku/node.go
cmd/waku/server/rest/admin.go
examples/basic-light-client/main.go
examples/basic-relay/main.go
examples/chat2/exec.go
examples/filter2/main.go
library/node.go
waku/v2/api/common/storenode_requestor.go
waku/v2/api/history/cycle.go
waku/v2/api/history/history.go
waku/v2/api/history/history_test.go
waku/v2/api/missing/criteria_interest.go
waku/v2/api/missing/default_requestor.go
waku/v2/api/missing/missing_messages.go
waku/v2/api/publish/default_verifier.go
waku/v2/api/publish/message_check.go
waku/v2/node/keepalive_test.go
waku/v2/node/wakunode2.go
waku/v2/node/wakunode2_test.go
waku/v2/peermanager/peer_manager.go
waku/v2/peermanager/peer_manager_test.go
waku/v2/protocol/filter/client.go
waku/v2/protocol/filter/test_utils.go
waku/v2/protocol/legacy_store/waku_store_client.go
waku/v2/protocol/lightpush/waku_lightpush.go
waku/v2/protocol/peer_exchange/client.go
waku/v2/protocol/store/client.go
waku/v2/protocol/store/options.go

Required by https://github.com/status-im/status-go/pull/5946
The interaction with libwaku is done thru multiaddresses instead of peerID, because the peerstore is not exposed like we do in go-waku. So, to make it possible to use both go-waku and nwaku in status-go (depending on a build flag), changes are done both in go-waku and the `api` package to use multiaddresses and/or peer.AddrInfo where needed.
It's worth mentioning that the cases in which a `peer.AddrInfo` are those in which a node can have more than one multiaddress (like the storenodes), and in these cases the `peer.AddrInfo` will be translated into a comma separated string containing all the multiaddresses like it is done here: https://github.com/status-im/status-go/blob/1348510acfdfd93dbe5fc5b0a23e9caf532272a3/wakuv2/nwaku.go#L …

refactor: use peerInfo and multiaddresses instead of peerID

---

waku/v2/protocol/store/client.go

Improving a small change introduced in https://github.com/waku-org/go-waku/pull/1269 which breaks the store queries in `status-go` 
https://github.com/status-im/status-go/issues/6439 and https://github.com/status-im/status-mobile/issues/22343

fix: setting peerId for store query

---

waku/v2/api/publish/rln_rate_limiting.go
waku/v2/api/publish/rln_rate_limiting_test.go

Persist the rate limit state with channel.
Related to: https://github.com/status-im/status-go/issues/6401

feat: send bucket update when rate limit applied

---

.github/docker-compose/nwaku.yml
waku/v2/api/publish/default_verifier.go

When querying for message hashes, we need to provide the multiaddresses containing the peer id, otherwise the query fails
https://github.com/status-im/status-desktop/issues/17774

fix: store query by hash

---

waku/v2/protocol/relay/subscription.go
waku/v2/protocol/relay/waku_relay.go
waku/v2/protocol/relay/waku_relay_test.go

1. I've removed this:
https://github.com/waku-org/go-waku/blob/8b0e03113db6db3dcd2fbef9a97380f2b8631098/waku/v2/protocol/relay/waku_relay.go#L441-L445
Because the client will call `Unsubscribe` in the end anyway. 
At the same time for current implementation we need to provide some `ctx`, which is complicating `status-go` code.
I've kept the `ctx` argument for `Subscribe` and `Unsubscribe` not to break compatibility.
2. Also added a getter for `Subscription.contentFilter` to simplify status-go code

fix: remove automatic relay unsubscribe in a goroutine

---

.github/docker-compose/nwaku.yml
.github/workflows/ci.yml
ci/Jenkinsfile.nix-flake
waku/v2/protocol/filter/server.go

1. Upgrade `golangci-lint` to v1.64.6
2. Fix some linter issues
3. Fix `nwaku` version used in storev3 tests, otherwise they fail. Upgrading to the latest one is probably not reasonable for this purpose.
4. `nix-flake` job fix by @jakubgs from https://github.com/waku-org/go-waku/pull/1290/commits
Required for https://github.com/waku-org/go-waku/pull/1288

ci: fix linter, storev3 tests and nix-flake jobs

---

.gitignore
Makefile

1. Codeclimate is dead
2. `go-waku` is being deprecated, so I think it's not worth it to replace CC with Codecov or anything else.

ci: remove codeclimate coverare reporting
